### PR TITLE
WINDUP-457 Move dir configs from WindupPathUtil to WindupConfigurationMo...

### PR DESCRIPTION
**Pull request by OndraZizka**
...del - does not work until Java 8

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder-illegalstate-fix/1/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/339/
Test FAILed.

**Comment by jsight** [comment]
I thought you were going to put these on WindupConfiguration.java ?

**Comment by lincolnthree** [comment]
Yeah, I could see some of these going onto WindupConfiguration, but definitely not WindupConfigurationModel.

**Comment by lincolnthree** [comment]
Rejected for now. I don't think this is an improvement.

**Pull request closed without merging**
