### PR TITLE
[WIP] - Separate freemarker

### PR DESCRIPTION
**Pull request by klinki**
In this PR I'm separating freemarker related code from reporting-api. I'm also modifying classes to be proxyable (adding empty protected constructor).

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
I'm kind of +0 on this at the moment. Feel free to keep using it if it helps you keep moving forward, but it may turn out not to be necessary.

We can sort out how to proceed when we are a little further along (whether with this or something else or a mixture of things).

**Comment by klinki** [comment]
I agree, with https://github.com/windup/windup-web/pull/75 this is probably not necessary anymore. Closing for now. Maybe we will get back to it sometimes later.

**Pull request closed without merging**
