### PR TITLE
WINDUP-890: Report Index: graph bars are hovered while cursor points …

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-890

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/767/<h2>Build result: FAILURE</span></h2>[...truncated 64520 lines...][ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/maven-plugin-usage/pom.xml to org.jboss.windup.quickstarts/maven-plugin-usage/2.5.0-SNAPSHOT/maven-plugin-usage-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/pom.xml to org.jboss.windup.jenkins/windup-core-dependents-aggregate-pom/2.3.0-SNAPSHOT/windup-core-dependents-aggregate-pom-2.3.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/pom.xml to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/pom.xml to org.jboss.windup.quickstarts/windup-quickstarts-root/2.5.0-SNAPSHOT/windup-quickstarts-root-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/pom.xml to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/classes/META-INF/resources/windup-victims-2.5.0-SNAPSHOT.dot to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT-forge-addon.jarchannel stoppedArchiving artifactsIRC notifier plugin: Sending notification to: #windupSetting status of 40d074a73102a3ff24047ba643282924277d9227 to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/767/ and message: 'Build finished. 5 tests run, 0 skipped, 0 failed.'

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1395/

**Comment by mareknovotny** [comment]
It seems ok although I can see not correlated shown values on both Number of findings / incidents bars graphs. See screenshot with my suggested correct number values in red
screenshot from 2016-01-28 10-53-32

**Comment by jsight** [comment]
@mareknovotny - That's what I get for testing with things that didn't have very many actual numbers. Basically, horizontal charts in flot work in a way that is a little unintuitive to me.

I've fixed it now, I think.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1404/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/778/

**Comment by mareknovotny** [comment]
@jsight it works!

**Pull request merged**
