### PR TITLE
WINDUP-1732 <annotation-list> w/o 'name' attribute

### PR DESCRIPTION
**Pull request by mrizzi**
This PR fixes the issue in [WINDUP-1732](https://issues.jboss.org/browse/WINDUP-1732)
- `org.jboss.windup.rules.apps.java.xml.JavaClassHandler#processElement` enhanced to better handle these three conditions:
  - `<annotation-type>` allows both blank and valued `name` attribute
  - `<annotation-list>` *now* allows blank `name` attribute to handle some nested annotation case, using the `value` value due to [`ReferenceResolvingVisitor.addAnnotationValues`](https://github.com/windup/windup/blob/master/java-ast/addon/src/main/java/org/jboss/windup/ast/java/ReferenceResolvingVisitor.java#L664)
  - `<annotation-literal>` does *not* allow blank `name` attribute
- `org.jboss.windup.rules.java.handlers.AnnotationConditionHandlerTest` tests (w/ test files `annotationcondition.[windup,rhamt].xml`) the `AnnotationListCondition` is added with `value` value
- `org.jboss.windup.rules.java.JavaClassAnnotationFilteringTest` tests (w/ test class `AnnotationMultipleDs`) that `org.jboss.windup.ast.java.ReferenceResolvingVisitor#addAnnotationValues` adds the nested annotations with `value` key

### CODE REVIEW

**Comment by mrizzi** [comment]
retest

**Comment by mrizzi** [comment]
retest

**Comment by mrizzi** [comment]
retest

**Comment by jsight** [comment]
Maybe this could have another test that covers the case of a missing "value" name? I think that this is good to go otherwise, though.

**Pull request merged**
