### PR TITLE
WINDUP-861 - Adjustments to the Source CSS.

### PR DESCRIPTION
**Pull request by bradsdavis**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1268/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/642/

**Comment by jsight** [comment]
@rdruss - http://imgur.com/BeCpIIp - This brings the border back and gets rid of the drop shadow. Ok to merge?

**Comment by rdruss** [comment]
@jsight +1

**Pull request merged**
