### PR TITLE
[WINDUP-3233] Fix version parsing

### PR DESCRIPTION
**Pull request by jmle**
Fixes the version comparison algorithm. See [WINDUP-3233](https://issues.redhat.com/browse/WINDUP-3233).

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@jmle haven't had the chance to run any regression tests yet. But the bug with the execution of the project base rule is fixed.
I'll do some regression tests when I return to work on Wednesday, then we'll get this fix merged to master. 
Thank you!

**Comment by carlosthe19916** [comment]
retest

**Comment by PhilipCattanach** [comment]
@jmle I have ran some regression tests and I am happy to report that they were all successful.
However the 3 out of the 4 automated checks have failed so I can't merge the PR.
Can you have a into what is causing our integration tests to fail please?

**Comment by PhilipCattanach** [comment]
Going to squash and merge as we have a deadlock with the automted tests.

**Pull request merged**
