### PR TITLE
switch to jboss-parent:20 and latest forge/furnace to accomodate java…

### PR DESCRIPTION
**Pull request by mareknovotny**
… 8 as minimal runtime/development environment

### CODE REVIEW

**Comment by mareknovotny** [comment]
retest

it seems wonka jenkins cannot request properly new furnace maven plugin from artifactory

**Comment by mareknovotny** [comment]
retest

**Comment by mareknovotny** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Pull request merged**
