### PR TITLE
WINDUP-812  Cache classification vertex lookups from the graph

### PR DESCRIPTION
**Pull request by OndraZizka**
An untested attempt

### CODE REVIEW

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Build triggered. sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build started sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build triggered. sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build finished. No test results found.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-core-PR-dependents-check/508/

**Comment by windupgithubbot1** [comment]
Build started sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build finished. No test results found.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-pr-builder/1137/

**Comment by jsight** [comment]
Have you seen any performance improvements from this?

**Comment by OndraZizka** [comment]
Haven't tried yet, I think this could get us some on larger apps.

**Comment by OndraZizka** [comment]
Testing

**Comment by OndraZizka** [comment]
It ran slightly faster. On a large app, it was from cca 136 minutes hours down to 135. :)  I have only tested it once.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1258/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/632/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1266/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/641/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1275/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/649/

**Comment by jsight** [comment]
The Map itself is not static, so the cache would only be used in cases where we cache the ClassificationService itself. I can't think of very many cases when we do that. In its current form, I don't think this PR can actually improve performance to a measurable degree.

**Pull request closed without merging**
