### PR TITLE
Add unparsable files to the jee-example-app

### PR DESCRIPTION
**Pull request by OndraZizka**
NEEDS #737

Will most likely break crash some rules with current master.
I am adding an invalid .properties, .xml, pom.xml and .class.
BTW, we might make a project to build this app.

### CODE REVIEW

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Build triggered. sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build triggered. sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build started sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build finished. No test results found.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-core-PR-dependents-check/509/

**Comment by windupgithubbot1** [comment]
Build started sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build finished. No test results found.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-pr-builder/1138/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='windup-pr-builder/org.jboss.windup.tests:windup-tests' /><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1138/org.jboss.windup.tests$windup-tests/testReport'>windup-pr-builder/org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>2</span></h3><ul><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1138/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/IgnoreJavaClassTest/testIgnoreFiles/'><strong>org.jboss.windup.tests.application.IgnoreJavaClassTest.testIgnoreFiles</strong></a></li><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1138/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li></ul>

**Comment by OndraZizka** [comment]
Actually, this is part of #737 .

**Pull request closed without merging**
