### PR TITLE
T914 cancel execution inside rule providers

### PR DESCRIPTION
**Pull request by OndraZizka**

### CODE REVIEW

**Comment by jsight** [comment]
retest

**Comment by OndraZizka** [comment]
Rebased

**Comment by jsight** [comment]
This isn't exactly perfect still, but I am going to go ahead and merge a modified version that seems to work pretty well.

Feel free to finish it up based on the latest master if you find issues.

**Comment by jsight** [comment]
I think the only remaining scenario is long running reports. We can defer that for now, though.

**Comment by OndraZizka** [comment]
I have tested this, and for some reason, event.shouldWindupStop() is false within the operations. Do we somewhere recreate the object? I'm now checking if it's the same one all the time or not

**Comment by OndraZizka** [comment]
It seems like I forgot to override DefaultRuleLifecycleListener's shouldWindupStop().

**Comment by jsight** [comment]
Yeah, I noticed that when I was testing it last night. :)

**Pull request closed without merging**
