### PR TITLE
CSV change ; to ,

### PR DESCRIPTION
**Pull request by mbriskar**
this change was requested by Tobias

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/396/
Test PASSed.

**Comment by mbriskar** [comment]
Maybe it may. I am however quite confused that having different delimeter is even an issue.

**Comment by jsight** [comment]
I agree with both of you. :)

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1025/
Test PASSed.

**Pull request merged**
