### PR TITLE
removing 3D shadows and changed label background color to be more con…

### PR DESCRIPTION
**Pull request by mareknovotny**
…trast

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1239/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/613/

**Comment by jsight** [comment]
Screenshots are here:

http://imgur.com/a/kcjzI

**Comment by mareknovotny** [comment]
screenshots seem wrong as tags are not grey :( I need to find out why .label-info is overwritten by color defined in bootstrap.

**Comment by mareknovotny** [comment]
I discovered that I had some mismatched comments in windup.css which caused to not load .label and .label-info styles properly. Not sure why as I thought // are comments in CSS too :(
So after changing them it looks like https://www.dropbox.com/s/1uk6xqj54jts1fb/Screenshot-labels.png?dl=0
I will sent another PR for that.

**Pull request merged**
