### PR TITLE
WINDUP-839: Send feedback links at the bottom of the application list and the top of the application overview page are broken

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-839

### CODE REVIEW

**Comment by jsight** [comment]
This also fixes the responsive layout issues on the overview page.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1264/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/638/

**Comment by mbriskar** [comment]
It does not work at my machine, just "#" is added to the link but nothing happens.

**Comment by mareknovotny** [comment]
it doesn't work on my environment. just curious how it could fix the the responsive layout issues on the overview page?

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/657/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1284/

**Comment by mareknovotny** [comment]
Ok, now it shows the Feedback dialog even on link in footer

**Comment by mareknovotny** [comment]
btw I like the feedback style flowing like in forge website here http://forge.jboss.org/news/forge-3.0.0.alpha3-is-here.
Wouldn't be better to use this style design and remove double link and menu item?

**Comment by jsight** [comment]
@mareknovotny  - An earlier version had it at the bottom in a similar style, but I believe that someone (maybe brad and lincoln) changed it. I do tend to prefer that style.

**Comment by mareknovotny** [comment]
well, I was thinking more on placing it on a side (forge has it on right side), but have it always visible as you scroll down or up.

**Pull request merged**
