### PR TITLE
WINDUP-709, WINDUP-704: The unbound classpath rule now only adds hint…

### PR DESCRIPTION
**Pull request by jsight**
…s if the line is not already hinted. Also, this makes the File condition return a FileLocationModel

https://issues.jboss.org/browse/WINDUP-709

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/355/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/984/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/984/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/984/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rule.groovy/GroovyExtensionJavaRulesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rule.groovy.GroovyExtensionJavaRulesTest.testHintsAndClassificationOperation</strong></a></li></ul>
Test FAILed.

**Comment by lincolnthree** [comment]
This looks crazy complicated :)

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/356/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/985/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/357/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/986/
Test PASSed.

**Pull request merged**
