### PR TITLE
Add XmlFile caching and escape { characters in rules

### PR DESCRIPTION
**Pull request by mbriskar**

### CODE REVIEW

**Comment by jsight** [comment]
@mbriskar Do you mind making the rule changes to the windup-rulesets repo?

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/512/<h2>Failed Tests: <span class='status-failure'>10</span></h2><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-ee-tests' /><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-ee-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport/org.jboss.windup.rules.apps.javaee.tests/DiscoverEjbConfigurationTest/testEJBMetadataExtraction/'><strong>org.jboss.windup.rules.apps.javaee.tests.DiscoverEjbConfigurationTest.testEJBMetadataExtraction</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-xml-tests' /><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-xml-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml.legacy/XmlJonasConfigTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.xml.legacy.XmlJonasConfigTest.testHintsAndClassificationOperation</strong></a></li></ul><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>8</span></h3><ul><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureHibernateTest/testRunWindupHibernate/'><strong>org.jboss.windup.tests.application.WindupArchitectureHibernateTest.testRunWindupHibernate</strong></a></li><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryModeTest/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryModeTest.testRunWindupTiny</strong></a></li><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSoa5GatewaysRoutersTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSoa5GatewaysRoutersTest.testRunWindupSourceMode</strong></a></li><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li><li><a href='https://windup-jenkins-os1.usersys.redhat.com/job/windup-pr-builder/512/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSpringSmallTest/testRunWindupSmallSpringApp/'><strong>org.jboss.windup.tests.application.WindupArchitectureSpringSmallTest.testRunWindupSmallSpringApp</strong></a></li></ul>
Test FAILed.

**Comment by lincolnthree** [comment]
Link to windup rulesets repository: https://github.com/windup/windup-rulesets

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/514/<h2>Failed Tests: <span class='status-failure'>10</span></h2><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-ee-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-ee-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport/org.jboss.windup.rules.apps.javaee.tests/DiscoverEjbConfigurationTest/testEJBMetadataExtraction/'><strong>org.jboss.windup.rules.apps.javaee.tests.DiscoverEjbConfigurationTest.testEJBMetadataExtraction</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-xml-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-xml-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml.legacy/XmlJonasConfigTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.xml.legacy.XmlJonasConfigTest.testHintsAndClassificationOperation</strong></a></li></ul><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>8</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureHibernateTest/testRunWindupHibernate/'><strong>org.jboss.windup.tests.application.WindupArchitectureHibernateTest.testRunWindupHibernate</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryModeTest/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryModeTest.testRunWindupTiny</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSoa5GatewaysRoutersTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSoa5GatewaysRoutersTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/514/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSpringSmallTest/testRunWindupSmallSpringApp/'><strong>org.jboss.windup.tests.application.WindupArchitectureSpringSmallTest.testRunWindupSmallSpringApp</strong></a></li></ul>
Test FAILed.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/515/<h2>Failed Tests: <span class='status-failure'>10</span></h2><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-ee-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-ee-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport/org.jboss.windup.rules.apps.javaee.tests/DiscoverEjbConfigurationTest/testEJBMetadataExtraction/'><strong>org.jboss.windup.rules.apps.javaee.tests.DiscoverEjbConfigurationTest.testEJBMetadataExtraction</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-xml-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-xml-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml.legacy/XmlJonasConfigTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.xml.legacy.XmlJonasConfigTest.testHintsAndClassificationOperation</strong></a></li></ul><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>8</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureHibernateTest/testRunWindupHibernate/'><strong>org.jboss.windup.tests.application.WindupArchitectureHibernateTest.testRunWindupHibernate</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryModeTest/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryModeTest.testRunWindupTiny</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSoa5GatewaysRoutersTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSoa5GatewaysRoutersTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/515/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSpringSmallTest/testRunWindupSmallSpringApp/'><strong>org.jboss.windup.tests.application.WindupArchitectureSpringSmallTest.testRunWindupSmallSpringApp</strong></a></li></ul>
Test FAILed.

**Pull request closed without merging**
