### PR TITLE
WINDUP-1274 - Removed port number. Turns out to be redundant since yo…

### PR DESCRIPTION
**Pull request by johnsteele**
…u need the port number in order to get the Windup ExecutionBuilder in the first place.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
@windupgithubbot1 test this please

**Comment by jsight** [comment]
I wondered this when I saw the initial patch. It seemed harmless, though. :)

I'll merge as soon as the test compile is done.

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
+1

**Pull request merged**
