### PR TITLE
WINDUP-437: Rules request: Integrate features from JBoss Tattletale

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-437

### CODE REVIEW

**Comment by mbriskar** [comment]
retest this please

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/337/
Test FAILed.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/338/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by lincolnthree** [comment]
Looks good for now. Ideally I'd like to see the tattletale report brought into the windup report natively (e.g. using our templates to display the information, but this is a fair first step.)

**Comment by lincolnthree** [comment]
This can be merged as soon as tests are verified passing.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/372/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.rules.apps:rules-java' /><a href='https://10.3.9.192/job/windup-pr-builder/372/org.jboss.windup.rules.apps$rules-java/testReport'>org.jboss.windup.rules.apps:rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/372/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/JavaClassCompositeTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassCompositeTest.testJavaClassCondition</strong></a></li></ul>
Test FAILed.

**Pull request merged**
