### PR TITLE
Static ip addresses

### PR DESCRIPTION
**Pull request by bradsdavis**
Adds report for static IP addresses when they exist in Java, Property, or XML files.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
PR sent with some modification... could you take a look?

https://github.com/bradsdavis/windup/pull/1

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/451/
Test PASSed.

**Comment by lincolnthree** [comment]
This is OK to merge as soon as @jsight's changes are merged. (Jess, you also have my permission to apply that patch locally, then merge.)

**Comment by lincolnthree** [comment]
(I reviewed both PRs)

**Comment by jsight** [comment]
@lincolnthree Thanks lincoln... I'll merge the two and push.

**Pull request merged**
