### PR TITLE
Updated POMs to use Windup BOM (Also upped Furnace version to Snapshot)

### PR DESCRIPTION
**Pull request by lincolnthree**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/426/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/427/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by jsight** [comment]
dist/pom.xml fails here as it cannot find version.forge. It does not appear that the properties from the bom are being imported to me.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/429/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/430/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by jsight** [comment]
Marking as adjustment required as the compile (dist) fails for me with this change.

**Comment by lincolnthree** [comment]
Really? I thought my latest change fixed that. I even emptied my org/jboss/windup repo folder :) Will check again.

**Comment by jsight** [comment]
doh, maybe I missed a pr sync. I'll try it again soon.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/434/
Test FAILed.

**Comment by jsight** [comment]
Tests pass locally... this is a huge improvement, IMO (and that's really understating it). Thanks!

**Pull request merged**
