### PR TITLE
WINDUP-277: Replace Migration 'Phases' with dependencies

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-277

This should give the basic idea for dep-based phases. The implementation itself appears to be working. The phases themselves are not documented and are just a partial implementation of what we had before. This won't be ready for a full review until they have been refactored to a more logic list of phases (and documented).

Do you consider this overall idea to be an improvement, though?

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/374/<h2>Failed Tests: <span class='status-failure'>7</span></h2><h3><a name='org.jboss.windup.config:windup-config-impl' /><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.config$windup-config-impl/testReport'>org.jboss.windup.config:windup-config-impl</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.config$windup-config-impl/testReport/org.jboss.windup.config.loader/WindupRuleProviderSorterTest/testSort/'><strong>org.jboss.windup.config.loader.WindupRuleProviderSorterTest.testSort</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.config$windup-config-impl/testReport/org.jboss.windup.config.loader/WindupRuleProviderSorterTest/testImproperCrossPhaseDependency/'><strong>org.jboss.windup.config.loader.WindupRuleProviderSorterTest.testImproperCrossPhaseDependency</strong></a></li></ul><h3><a name='org.jboss.windup.config:windup-config-xml' /><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.config$windup-config-xml/testReport'>org.jboss.windup.config:windup-config-xml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.config$windup-config-xml/testReport/org.jboss.windup.config.parser/XMLRuleProviderLoaderTest/testGetProviders/'><strong>org.jboss.windup.config.parser.XMLRuleProviderLoaderTest.testGetProviders</strong></a></li></ul><h3><a name='org.jboss.windup.ext:windup-config-groovy' /><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.ext$windup-config-groovy/testReport'>org.jboss.windup.ext:windup-config-groovy</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.ext$windup-config-groovy/testReport/org.jboss.windup.addon.groovy/LoadGroovyRulesTest/testGroovyRuleProviderFactory/'><strong>org.jboss.windup.addon.groovy.LoadGroovyRulesTest.testGroovyRuleProviderFactory</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.ext$windup-config-groovy/testReport/org.jboss.windup.addon.groovy/LoadGroovyRulesTest/testGroovyUserDirectoryRuleProvider/'><strong>org.jboss.windup.addon.groovy.LoadGroovyRulesTest.testGroovyUserDirectoryRuleProvider</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-java' /><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.rules.apps$rules-java/testReport'>org.jboss.windup.rules.apps:rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rule.groovy/GroovyExtensionJavaRulesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rule.groovy.GroovyExtensionJavaRulesTest.testHintsAndClassificationOperation</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-xml' /><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.rules.apps$rules-xml/testReport'>org.jboss.windup.rules.apps:rules-xml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/374/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.apps.xml.groovy/GroovyExtensionXmlRulesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.apps.xml.groovy.GroovyExtensionXmlRulesTest.testHintsAndClassificationOperation</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/377/<h2>Failed Tests: <span class='status-failure'>7</span></h2><h3><a name='org.jboss.windup.config:windup-config-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.config$windup-config-tests/testReport'>org.jboss.windup.config:windup-config-tests</a>: <span class='status-failure'>5</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.iteration.payload.when/RuleIterationWhenTest/testTypeSelection/'><strong>org.jboss.windup.config.iteration.payload.when.RuleIterationWhenTest.testTypeSelection</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.selectables/VariablesTest/testInvalidCountGet/'><strong>org.jboss.windup.config.selectables.VariablesTest.testInvalidCountGet</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.selectables/VariablesTest/testUnTypedGet/'><strong>org.jboss.windup.config.selectables.VariablesTest.testUnTypedGet</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.selectables/VariablesTest/testMultipleFramesSameName/'><strong>org.jboss.windup.config.selectables.VariablesTest.testMultipleFramesSameName</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.selectables/VariablesTest/testInvalidTypeGet/'><strong>org.jboss.windup.config.selectables.VariablesTest.testInvalidTypeGet</strong></a></li></ul><h3><a name='org.jboss.windup.reporting:windup-reporting-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.reporting$windup-reporting-tests/testReport'>org.jboss.windup.reporting:windup-reporting-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.reporting$windup-reporting-tests/testReport/org.jboss.windup.reporting/ApplicationReportIndexModelServiceTest/testGetApplicationReportsForProjectModelSortedByPriority/'><strong>org.jboss.windup.reporting.ApplicationReportIndexModelServiceTest.testGetApplicationReportsForProjectModelSortedByPriority</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-xml' /><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.rules.apps$rules-xml/testReport'>org.jboss.windup.rules.apps:rules-xml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/377/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.apps.xml.groovy/GroovyExtensionXmlRulesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.apps.xml.groovy.GroovyExtensionXmlRulesTest.testHintsAndClassificationOperation</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/382/<h2>Failed Tests: <span class='status-failure'>18</span></h2><h3><a name='org.jboss.windup.config:windup-config-impl' /><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.config$windup-config-impl/testReport'>org.jboss.windup.config:windup-config-impl</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.config$windup-config-impl/testReport/org.jboss.windup.config.loader/WindupRuleProviderSorterTest/testSort/'><strong>org.jboss.windup.config.loader.WindupRuleProviderSorterTest.testSort</strong></a></li></ul><h3><a name='org.jboss.windup.config:windup-config-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.config$windup-config-tests/testReport'>org.jboss.windup.config:windup-config-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.iteration/RuleIterationOverDefaultSingleVariableTest/testTypeSelection/'><strong>org.jboss.windup.config.iteration.RuleIterationOverDefaultSingleVariableTest.testTypeSelection</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-base-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-base-tests/testReport'>org.jboss.windup.rules.apps:rules-base-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-base-tests/testReport/org.jboss.windup.rules.apps.condition/FileContentTest/testFileContentScan/'><strong>org.jboss.windup.rules.apps.condition.FileContentTest.testFileContentScan</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-java' /><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-java/testReport'>org.jboss.windup.rules.apps:rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.apps.java.service/TypeReferenceServiceTest/testGetPackageUseFrequencies/'><strong>org.jboss.windup.rules.apps.java.service.TypeReferenceServiceTest.testGetPackageUseFrequencies</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-xml' /><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-xml/testReport'>org.jboss.windup.rules.apps:rules-xml</a>: <span class='status-failure'>7</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.apps.xml.groovy/GroovyExtensionXmlRulesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.apps.xml.groovy.GroovyExtensionXmlRulesTest.testHintsAndClassificationOperation</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml/XMLFileNestedConditionTest/testNestedCondition/'><strong>org.jboss.windup.rules.xml.XMLFileNestedConditionTest.testNestedCondition</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml/XMLHintsClassificationsTest/testHintAndClassificationOperation/'><strong>org.jboss.windup.rules.xml.XMLHintsClassificationsTest.testHintAndClassificationOperation</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml/XMLTransformationTest/testXSLTTransformation/'><strong>org.jboss.windup.rules.xml.XMLTransformationTest.testXSLTTransformation</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParams/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParams</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParamsDangling/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParamsDangling</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParamsMultiCondition/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParamsMultiCondition</strong></a></li></ul><h3><a name='org.jboss.windup.tests:tests' /><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.tests$tests/testReport'>org.jboss.windup.tests:tests</a>: <span class='status-failure'>7</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureHibernateTest/testRunWindupHibernate/'><strong>org.jboss.windup.tests.application.WindupArchitectureHibernateTest.testRunWindupHibernate</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureScanPackagesTest/testRunWindupScanPackages/'><strong>org.jboss.windup.tests.application.WindupArchitectureScanPackagesTest.testRunWindupScanPackages</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryMode2Test/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryMode2Test.testRunWindupTiny</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryModeTest/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryModeTest.testRunWindupTiny</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/382/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSpringSmallTest/testRunWindupSmallSpringApp/'><strong>org.jboss.windup.tests.application.WindupArchitectureSpringSmallTest.testRunWindupSmallSpringApp</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/385/<h2>Failed Tests: <span class='status-failure'>7</span></h2><h3><a name='org.jboss.windup.tests:tests' /><a href='https://10.3.9.192/job/windup-pr-builder/385/org.jboss.windup.tests$tests/testReport'>org.jboss.windup.tests:tests</a>: <span class='status-failure'>7</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/385/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureHibernateTest/testRunWindupHibernate/'><strong>org.jboss.windup.tests.application.WindupArchitectureHibernateTest.testRunWindupHibernate</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/385/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/385/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/385/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureScanPackagesTest/testRunWindupScanPackages/'><strong>org.jboss.windup.tests.application.WindupArchitectureScanPackagesTest.testRunWindupScanPackages</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/385/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryMode2Test/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryMode2Test.testRunWindupTiny</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/385/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryModeTest/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryModeTest.testRunWindupTiny</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/385/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSpringSmallTest/testRunWindupSmallSpringApp/'><strong>org.jboss.windup.tests.application.WindupArchitectureSpringSmallTest.testRunWindupSmallSpringApp</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test PASSed.

**Comment by windupgithubbot1** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/387/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/389/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup.reporting:windup-reporting-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/389/org.jboss.windup.reporting$windup-reporting-tests/testReport'>org.jboss.windup.reporting:windup-reporting-tests</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/389/org.jboss.windup.reporting$windup-reporting-tests/testReport/org.jboss.windup.reporting/InlineHintModelQueryTest/testFindingClassifiedFiles/'><strong>org.jboss.windup.reporting.InlineHintModelQueryTest.testFindingClassifiedFiles</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/389/org.jboss.windup.reporting$windup-reporting-tests/testReport/org.jboss.windup.reporting/InlineHintModelQueryTest/testFindingNonClassifiedFiles/'><strong>org.jboss.windup.reporting.InlineHintModelQueryTest.testFindingNonClassifiedFiles</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test PASSed.

**Comment by windupgithubbot1** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/390/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/391/<h2>Failed Tests: <span class='status-failure'>7</span></h2><h3><a name='org.jboss.windup.config:windup-config-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.config$windup-config-tests/testReport'>org.jboss.windup.config:windup-config-tests</a>: <span class='status-failure'>4</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.selectables/VariablesTest/testInvalidCountGet/'><strong>org.jboss.windup.config.selectables.VariablesTest.testInvalidCountGet</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.selectables/VariablesTest/testUnTypedGet/'><strong>org.jboss.windup.config.selectables.VariablesTest.testUnTypedGet</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.selectables/VariablesTest/testMultipleFramesSameName/'><strong>org.jboss.windup.config.selectables.VariablesTest.testMultipleFramesSameName</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.selectables/VariablesTest/testInvalidTypeGet/'><strong>org.jboss.windup.config.selectables.VariablesTest.testInvalidTypeGet</strong></a></li></ul><h3><a name='org.jboss.windup.ext:windup-config-groovy' /><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.ext$windup-config-groovy/testReport'>org.jboss.windup.ext:windup-config-groovy</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.ext$windup-config-groovy/testReport/org.jboss.windup.addon.groovy/LoadGroovyRulesTest/testGroovyRuleProviderFactory/'><strong>org.jboss.windup.addon.groovy.LoadGroovyRulesTest.testGroovyRuleProviderFactory</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.ext$windup-config-groovy/testReport/org.jboss.windup.addon.groovy/LoadGroovyRulesTest/testGroovyUserDirectoryRuleProvider/'><strong>org.jboss.windup.addon.groovy.LoadGroovyRulesTest.testGroovyUserDirectoryRuleProvider</strong></a></li></ul><h3><a name='org.jboss.windup.reporting:windup-reporting-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.reporting$windup-reporting-tests/testReport'>org.jboss.windup.reporting:windup-reporting-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/391/org.jboss.windup.reporting$windup-reporting-tests/testReport/org.jboss.windup.reporting/ApplicationReportIndexModelServiceTest/testGetApplicationReportsForProjectModelSortedByPriority/'><strong>org.jboss.windup.reporting.ApplicationReportIndexModelServiceTest.testGetApplicationReportsForProjectModelSortedByPriority</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/392/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup.rules.apps:rules-java' /><a href='https://10.3.9.192/job/windup-pr-builder/392/org.jboss.windup.rules.apps$rules-java/testReport'>org.jboss.windup.rules.apps:rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/392/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java.ignore/JavaIgnoreRegexesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.java.ignore.JavaIgnoreRegexesTest.testHintsAndClassificationOperation</strong></a></li></ul><h3><a name='org.jboss.windup.tests:tests' /><a href='https://10.3.9.192/job/windup-pr-builder/392/org.jboss.windup.tests$tests/testReport'>org.jboss.windup.tests:tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/392/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureScanPackagesTest/testRunWindupScanPackages/'><strong>org.jboss.windup.tests.application.WindupArchitectureScanPackagesTest.testRunWindupScanPackages</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test PASSed.

**Comment by windupgithubbot1** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/393/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/394/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup.graph:windup-graph-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/394/org.jboss.windup.graph$windup-graph-tests/testReport'>org.jboss.windup.graph:windup-graph-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/394/org.jboss.windup.graph$windup-graph-tests/testReport/org.jboss.windup.graph.typedgraph/InMemoryFrameTest/testInMemoryFrame/'><strong>org.jboss.windup.graph.typedgraph.InMemoryFrameTest.testInMemoryFrame</strong></a></li></ul><h3><a name='org.jboss.windup.tests:tests' /><a href='https://10.3.9.192/job/windup-pr-builder/394/org.jboss.windup.tests$tests/testReport'>org.jboss.windup.tests:tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/394/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureScanPackagesTest/testRunWindupScanPackages/'><strong>org.jboss.windup.tests.application.WindupArchitectureScanPackagesTest.testRunWindupScanPackages</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/395/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.rules.apps:rules-java' /><a href='https://10.3.9.192/job/windup-pr-builder/395/org.jboss.windup.rules.apps$rules-java/testReport'>org.jboss.windup.rules.apps:rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/395/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/JavaClassCompositeTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassCompositeTest.testJavaClassCondition</strong></a></li></ul>
Test FAILed.

**Comment by lincolnthree** [comment]
Merged.

**Pull request closed without merging**
