### PR TITLE
WINDUPRULE-331: Also made it possible to use iteration filtering in t…

### PR DESCRIPTION
**Pull request by jsight**
…he way that a user would expect

### CODE REVIEW

**Comment by mrizzi** [comment]
retest

**Comment by jsight** [comment]
Moving back to WIP... looks like there is a intermittent test failure, so I should probably think about the annotation test a little more.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
@mrizzi - I think this is ready to review again.

**Pull request merged**
