### PR TITLE
Edge discriminator is not stored to the properties

### PR DESCRIPTION
**Pull request by OndraZizka**

### CODE REVIEW

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
It looks like this is causing a lot of test failures.

**Comment by OndraZizka** [comment]
Edge doesn't support addProperty(), there's a little inconsistence in Titan API...
So instead I revived the |-separated concept. Although, edges will most likely only have a single model - having more for a single edge doesn't make much sense.
I'm not sure if I put the necessary functionality everywhere.

**Comment by jsight** [comment]
retest

**Comment by OndraZizka** [comment]
What build is pending? I can't connect to VPN so I can't see wonka.

**Comment by mareknovotny** [comment]
@OndraZizka I don't know, but it seems that after I changed the contexts, this PR can't handle the updates.
There are only 2 jobs and they passes. The default context is suspicious now.

**Comment by mareknovotny** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
reviewing now...

**Comment by jsight** [comment]
lgtm, merged. :)

**Pull request merged**
