### PR TITLE
WINDUP-810 - Fixed missing macro from merge issue.

### PR DESCRIPTION
**Pull request by bradsdavis**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-pr-builder/1132/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-core-PR-dependents-check/502/
Test PASSed.

**Comment by OndraZizka** [comment]
Thanks!

**Comment by jsight** [comment]
Thanks @bradsdavis ! This was probably my fault in a rebase (oops). A few of these rebases ended up being a bit complicated.

**Pull request merged**
