### PR TITLE
Topology graph fix - Display JAR apps and JARs in JARs

### PR DESCRIPTION
**Pull request by Maarc**
This is a fix for the topology graph currently unfortunately broken for "JAR" applications.

The fix adds a node to display "JAR" applications and "JAR" libraries embedded within another "JAR".

### CODE REVIEW

**Comment by Maarc** [comment]
Example with this fix ... 
image

... and the same applications without the fix:
image

**Review by mrizzi — CHANGES_REQUESTED** [review]
Hey Marc,
nice to "hear" from you again, I hope you're doing great.
I've checked your PR and I've figured out that the added `g` tag in [1] caused failures in 2 tests:
- WindupArchitectureDuplicateTest.testRunWindupDuplicateEAR:88->validateJarDependencyGraphReport:208 expected:<18> but was:<19>
- WindupArchitectureExplodedAppTest.testRunWindupExplodedApp:65->validateJarDependencyGraphReport:76 expected:<21> but was:<22>

Could you:

1. merge latest master branch into your PR (we released over the last days)
2. update the [WindupArchitectureDuplicateTest:208](https://github.com/windup/windup/blob/3c44bf147d75a5661029161ca6956c2e88518f9a/tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java#L208) and [WindupArchitectureExplodedAppTest:76](https://github.com/windup/windup/blob/3c44bf147d75a5661029161ca6956c2e88518f9a/tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureExplodedAppTest.java#L76) to expect, respectively, 19 and 22 `NumberOfArchivesInTheGraph`

Thanks a lot 👍

[1] https://github.com/windup/windup/pull/1632/files#diff-86585e750e28ec8885e29238c51c6c2b513288cb46efec212510142ce265033aR126-R129

**Comment by Maarc** [comment]
Hi Marco!

It is great to read you again :-) I just have been through the suggested changes.

It would be nice if you could add this to the 6.1.9 , as the version 6.2.0 seem to completely reset the UX, dependency graph, list of apps, and technologies.

I wanted to push this change for a very long time. I am glad I finally did it.

Best regards,

Marc

**Review by mrizzi — APPROVED** [review]
@Maarc thanks a lot :+1:

**Comment by Maarc** [comment]
@mrizzi : Hey Marco!

Is there any chance you could merge this PR on the "6.1.x" tagged branch as well?

On the 6.2.x it does not make much sense as most of the visualizations have been removed. The PR did not make it to the 6.1.11 version.

Best regards,

Marc

**Comment by mrizzi** [comment]
@Maarc hi! Thanks for raising the question.

I think we could evaluate the backport but it's kind of bad timing due to some upcoming PTO.
So it's absolutely not excluded we'll backport this but it can not happen right now.

We'll come back to evaluate this after July 17th.

**Comment by mrizzi** [comment]
@Maarc hi!
Backport done and merged in https://github.com/windup/windup/pull/1691 :wink:

**Comment by Maarc** [comment]
Thank you @mrizzi ! Is there a chance you could provide a 6.1.12 for it?

The later releases (6.2.x and 6.3.x) dropped the visualizations.

**Comment by mrizzi** [comment]
@Maarc hi!
There's no plan to have further releases in the `6.1.z` branch at the moment.
But you can leverage the `--legacyReports` with the latest Windup versions to still get the "old" reports generated.

**Comment by Maarc** [comment]
Great! Thanks for the info.

**Pull request merged**
