### PR TITLE
<classification classfification="..." -> title="..."

### PR DESCRIPTION
**Pull request by OndraZizka**
Needs also XSD change. But I did it through github editor.

### CODE REVIEW

**Comment by lincolnthree** [comment]
Are there any test cases that depend on this?

**Comment by lincolnthree** [comment]
Such as ClassificationHandlerTest

**Comment by lincolnthree** [comment]
Fixed tests and merged.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/168/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.rules:windup-rulesets' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/168/org.jboss.windup.rules$windup-rulesets/testReport'>org.jboss.windup.rules:windup-rulesets</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/168/org.jboss.windup.rules$windup-rulesets/testReport/org.jboss.windup.rules.tests/WindupRulesTest/testWindupRules/'><strong>org.jboss.windup.rules.tests.WindupRulesTest.testWindupRules</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/803/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.reporting:windup-reporting-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/803/org.jboss.windup.reporting$windup-reporting-tests/testReport'>org.jboss.windup.reporting:windup-reporting-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/803/org.jboss.windup.reporting$windup-reporting-tests/testReport/org.jboss.windup.reporting.handlers/ClassificationHandlerTest/testClassificationParsing/'><strong>org.jboss.windup.reporting.handlers.ClassificationHandlerTest.testClassificationParsing</strong></a></li></ul>
Test FAILed.

**Pull request closed without merging**
