### PR TITLE
WINDUP-581 - Added tags and classification for maven

### PR DESCRIPTION
**Pull request by bradsdavis**
Added technology tags for Maven and Classification for Maven.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/88/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/717/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup:windup-tooling-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/717/org.jboss.windup$windup-tooling-tests/testReport'>org.jboss.windup:windup-tooling-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/717/org.jboss.windup$windup-tooling-tests/testReport/org.jboss.windup.tooling/ExecutionBuilderTest/testExecutionBuilder/'><strong>org.jboss.windup.tooling.ExecutionBuilderTest.testExecutionBuilder</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-archives-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/717/org.jboss.windup.rules.apps$windup-rules-java-archives-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-archives-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/717/org.jboss.windup.rules.apps$windup-rules-java-archives-tests/testReport/org.jboss.windup.rules.apps.java.archives/IgnoreArchivesRulesetTest/testSkippedArchivesFound/'><strong>org.jboss.windup.rules.apps.java.archives.IgnoreArchivesRulesetTest.testSkippedArchivesFound</strong></a></li></ul>
Test FAILed.

**Comment by lincolnthree** [comment]
test this please

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/749/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup:windup-tooling-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/749/org.jboss.windup$windup-tooling-tests/testReport'>org.jboss.windup:windup-tooling-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/749/org.jboss.windup$windup-tooling-tests/testReport/org.jboss.windup.tooling/ExecutionBuilderTest/testExecutionBuilder/'><strong>org.jboss.windup.tooling.ExecutionBuilderTest.testExecutionBuilder</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-archives-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/749/org.jboss.windup.rules.apps$windup-rules-java-archives-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-archives-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/749/org.jboss.windup.rules.apps$windup-rules-java-archives-tests/testReport/org.jboss.windup.rules.apps.java.archives/IgnoreArchivesRulesetTest/testSkippedArchivesFound/'><strong>org.jboss.windup.rules.apps.java.archives.IgnoreArchivesRulesetTest.testSkippedArchivesFound</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/117/
Test PASSed.

**Pull request closed without merging**
