### PR TITLE
WINDUP-464: Split simple layout projects into addon/tests (or addon/api/...

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-464

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/504/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/505/
Test PASSed.

**Comment by lincolnthree** [comment]
Merged. Nice work!

**Comment by jsight** [comment]
Thanks! :)

**Pull request closed without merging**
