### PR TITLE
T842 Add the path to the archive that failed to unzip

### PR DESCRIPTION
**Pull request by OndraZizka**
The task wanted a link. But is that the right solution? Is the user expected to download it and try to unzip manually? Although, we would have to store the archive exceptionally as a part of the report, which we normally don't do unless --keepWorkDirs .

So I am only adding the path.

### CODE REVIEW

**Comment by OndraZizka** [comment]
I have tried to test this but it seems the unparsable.jar in our sample .ear isn't processed.

**Comment by OndraZizka** [comment]
The file is being skipped entirely, needs debugging.

**Comment by mareknovotny** [comment]
retest

**Comment by mareknovotny** [comment]
retest - after fixing windup-rulesets master

**Comment by mareknovotny** [comment]
retest

**Comment by jsight** [comment]
I think that it should only show the path instead of adding a link.

**Comment by OndraZizka** [comment]
Now I looked at it closer and the thing is that the file name doesn't appear. This PR makes the issue have the file name but I guess it wouldn't appear in the report. However I can't make the invalid zipfile appear at all.

**Comment by OndraZizka** [comment]
@jsight  Where are ClassificationModels converted to HintModels? At least that's my assumption, see my comment at https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/842?kanban-status=543761

**Comment by OndraZizka** [comment]
Ok never mind, I read on and found that it's iterating over clsf too...

**Comment by OndraZizka** [comment]
So the bug goes down to 
```
{l:"${renderedLink?json_string}", oc:"${fileSummary.occurrences?json_string}"},
```
looking at what exactly is wrong

**Comment by OndraZizka** [comment]
Ok now it should be fixed properly. Works for me.

**Comment by mareknovotny** [comment]
@OndraZizka  Do you  have somewhere test case or what application is producing the output for Malformed zip file?

**Pull request merged**
