### PR TITLE
Added in icons for the remaining reports.

### PR DESCRIPTION
**Pull request by bradsdavis**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by bradsdavis** [comment]
Added in additional icons for remaining.

**Comment by jsight** [comment]
@windupgithubbot1 test this please

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/458/
Test PASSed.

**Pull request merged**
