### PR TITLE
Taiga t262

### PR DESCRIPTION
**Pull request by mareknovotny**
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/262

### CODE REVIEW

**Comment by mareknovotny** [comment]
Beside failed tests - maven artifact downloads still is not stable, there are some questions.

I did filtering based on phases, but this could be wrong. If it is, the question is how to get list of rules which are preparing/producing reports. For instance exporting csv is in report related phases too.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
@mareknovotny - BTW, I fixed the maven artifact thing. Today it was related to a weird issue with forge downloading deps from the wrong repo.

**Comment by mareknovotny** [comment]
@jsight thanks! I fixed the NPE in tests and added handling of skipReports option in bootstrap

**Comment by d-s** [comment]
@jsight This was the other open PR I was thinking of, John is near a point of being blocked behind this one on his other story, not sure how much you have reviewed it already but it'd be good if you can go over it and we can get it merged tomorrow, looks like it should be almost done.

**Comment by jsight** [comment]
Oh, I didn't realize that this was a blocker. I looked at it yesterday and it seemed to be in good shape. 

+1 from me.

**Pull request merged**
