### PR TITLE
Split GraphTypeManager so it keeps edge types separatedly.

### PR DESCRIPTION
**Pull request by OndraZizka**
Trying to fix the tests errors.

### CODE REVIEW

**Comment by OndraZizka** [comment]
Locally, the tests still fail. So it's not caused by presence of new types in the GTM.

**Comment by mareknovotny** [comment]
it seems, there are more failures than after @jsight 's changes

**Comment by OndraZizka** [comment]
http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1968/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.apps.java/ClassMetadataTest/testJavaSourceScanning/

**Comment by OndraZizka** [comment]
http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1968/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.apps.java/ClassMetadataTest/testJavaSourceScanning/

**Pull request closed without merging**
