### PR TITLE
WINDUP-612  Validate all XML rules in windup-rulesets during build.

### PR DESCRIPTION
**Pull request by OndraZizka**
Comes with https://github.com/windup/windup-rulesets/pull/17

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/151/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.rules:windup-rulesets' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/151/org.jboss.windup.rules$windup-rulesets/testReport'>org.jboss.windup.rules:windup-rulesets</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/151/org.jboss.windup.rules$windup-rulesets/testReport/org.jboss.windup.rules.tests/WindupRulesTest/testWindupRules/'><strong>org.jboss.windup.rules.tests.WindupRulesTest.testWindupRules</strong></a></li></ul>
Test FAILed.

**Comment by lincolnthree** [comment]
We need to re-think how this is done.

**Comment by lincolnthree** [comment]
This looks to me like we are just creating another copy of the schema. We can't maintain this in two places.

**Comment by mareknovotny** [comment]
Why not to do that in build process like copy-resources just for bundling it into artifact? So we would still have only one place for editing/maintaining.

**Comment by OndraZizka** [comment]
@lincolnthree , what copy? Why should a working temporary copy in /target matter?

**Comment by OndraZizka** [comment]
This should have been a rename, not a copy. I made something wrong in git. But still: The pom should package this into the .jar.

**Pull request closed without merging**
