### PR TITLE
WINDUP-798: Ensure that IP addresses are identifed for only n.n.n.n p…

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-798

### CODE REVIEW

**Comment by rdruss** [comment]
Should a test be added to ensure an n.n.n.n.n pattern is *not* matched?

**Comment by rdruss** [comment]
Would the unexpected match be this:

unexpectedIPs.add("192.168.0.9.3.4");
-or-
unexpectedIPs.add("192.168.0.9");

I know in the false positives in the report, it looks like a valid IP address until you look at the source.

**Comment by jsight** [comment]
In theory, it could be either one or even something else entirely. Having said that, there is an assertion at the end to try to catch this:

Assert.assertEquals(expectedIPs.size(), numberFound);

Basically, if we get anything that is in the expected list we fail, and we also fail if we get anything that is in neither list.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/471/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1102/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/472/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1103/
Test PASSed.

**Pull request merged**
