### PR TITLE
Fixed markup - RuleProviderSummary and FreemarkerFunctions pages

### PR DESCRIPTION
**Pull request by Maarc**
Fixed the markup for the RuleProviderSummary and the FreemarkerFuctions pages.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
@windupgithubbot1 retest

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1064/
Test PASSed.

**Comment by jsight** [comment]
This looks really nice... thanks @Maarc !

**Pull request merged**
