### PR TITLE
WINDUP-1125 US601 Support Location References for Project Archive T602/603

### PR DESCRIPTION
**Pull request by mrizzi**
Done:

- #602Add Iterable of FileLocationModels to ProjectDependencyModel
- #603Update places that create ProjectDependencyModel to attach file location information 

but still getting the following NPE (the same as in [WINDUP-1125](https://issues.jboss.org/browse/WINDUP-1125))
Failed when iterating [v[10240]={w:winduptype: [MavenFacet, ProjectModel], mavenIdentifier: com.redhat:examples:1.0-SNAPSHOT, groupId: com.redhat, name: springboot-data, artifactId: examples, version: 1.0-SNAPSHOT, specificationVersion: 4.0.0}], due to: null
org.jboss.windup.util.exception.WindupException: Failed when iterating [v[10240]={w:winduptype: [MavenFacet, ProjectModel], mavenIdentifier: com.redhat:examples:1.0-SNAPSHOT, groupId: com.redhat, name: springboot-data, artifactId: examples, version: 1.0-SNAPSHOT, specificationVersion: 4.0.0}], due to: null
        at org.jboss.windup.config.operation.Iteration.perform(Iteration.java:294)
        at org.jboss.windup.config.operation.Iteration.perform(Iteration.java:207)
        at org.ocpsoft.rewrite.config.RuleBuilder.perform(RuleBuilder.java:168)
        at org.jboss.windup.config.RuleSubset.perform(RuleSubset.java:289)
        at org.jboss.windup.exec.WindupProcessorImpl.execute(WindupProcessorImpl.java:171)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
        at org.jboss.windup.exec.WindupProcessorImpl_$$_javassist_8c50c146-960e-480b-84dd-a2e55fc8a01e.execute(WindupProcessorImpl_$$_javassist_8c50c146-960e-480b-84dd-a2e55fc8a01e.java)
        at org.jboss.windup.rules.tests.WindupRulesTest.runWindup(WindupRulesTest.java:351)
        at org.jboss.windup.rules.tests.WindupRulesTest.access$500(WindupRulesTest.java:74)
        at org.jboss.windup.rules.tests.WindupRulesTest$RuleTestVisitor.visit(WindupRulesTest.java:225)
        at org.jboss.windup.rules.tests.WindupRulesTest$RuleTestVisitor.visit(WindupRulesTest.java:148)
        at org.jboss.windup.util.file.FileVisit.visit(FileVisit.java:34)
        at org.jboss.windup.rules.tests.WindupRulesTest.testWindupRules(WindupRulesTest.java:124)
        [...]
Caused by: java.lang.NullPointerException
        at org.jboss.windup.config.parameters.ParameterizedIterationOperation.perform(ParameterizedIterationOperation.java:70)
        at org.jboss.windup.config.operation.iteration.AbstractIterationOperation.perform(AbstractIterationOperation.java:65)
        at org.jboss.windup.config.parameters.ParameterizedIterationOperation.perform(ParameterizedIterationOperation.java:45)
        at org.jboss.windup.config.operation.GraphOperation.perform(GraphOperation.java:24)
        at org.ocpsoft.rewrite.config.DefaultOperationBuilder$DefaultOperationBuilderInternal.perform(DefaultOperationBuilder.java:55)
        at org.jboss.windup.config.operation.Iteration.perform(Iteration.java:267)
        ... 116 more

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by mrizzi** [comment]
@jsight thanks for the help!

**Comment by jsight** [comment]
@mrizzi - I think that this is ready to merge if the code is all working for you?

**Comment by mrizzi** [comment]
@jsight yes, it can be merged for me too.

**Pull request merged**
