### PR TITLE
Upgrade Titan to 0.5.4. Numerous bugfixes.

### PR DESCRIPTION
**Pull request by OndraZizka**
http://s3.thinkaurelius.com/docs/titan/current/changelog.html

### CODE REVIEW

**Comment by OndraZizka** [comment]
Also, Frames 2.6.0 "Added pluggable type resolver system".
https://github.com/tinkerpop/frames/wiki/Release-Notes

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/599/
Test PASSed.

**Comment by jsight** [comment]
@OndraZizka - Check the author tag on that feature. :)

**Comment by OndraZizka** [comment]
Ah, right, that's your addition. Congratulations :)

**Pull request merged**
