### PR TITLE
WINDUP-940 Only process files a single time if the same archive is included more…

### PR DESCRIPTION
**Pull request by jsight**
This needs more work to work with Procyon as well.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1391/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='windup-pr-builder/org.jboss.windup.tests:windup-tests' /><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1391/org.jboss.windup.tests$windup-tests/testReport'>windup-pr-builder/org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1391/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureTestKeepArchivesAndGraphTest/testRunWindupDiscard/'><strong>org.jboss.windup.tests.application.WindupArchitectureTestKeepArchivesAndGraphTest.testRunWindupDiscard</strong></a></li></ul>

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/763/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/765/<h2>Build result: FAILURE</span></h2>[...truncated 64967 lines...][ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/maven-plugin-usage/pom.xml to org.jboss.windup.quickstarts/maven-plugin-usage/2.5.0-SNAPSHOT/maven-plugin-usage-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/pom.xml to org.jboss.windup.jenkins/windup-core-dependents-aggregate-pom/2.3.0-SNAPSHOT/windup-core-dependents-aggregate-pom-2.3.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/pom.xml to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/pom.xml to org.jboss.windup.quickstarts/windup-quickstarts-root/2.5.0-SNAPSHOT/windup-quickstarts-root-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/pom.xml to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/classes/META-INF/resources/windup-victims-2.5.0-SNAPSHOT.dot to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT-forge-addon.jarchannel stoppedArchiving artifactsIRC notifier plugin: Sending notification to: #windupSetting status of d13ec205cd6f813a7e647be7c00ee9e67ff6d49b to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/765/ and message: 'Build finished. 5 tests run, 0 skipped, 0 failed.'

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1393/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/766/<h2>Build result: FAILURE</span></h2>[...truncated 64769 lines...][ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/maven-plugin-usage/pom.xml to org.jboss.windup.quickstarts/maven-plugin-usage/2.5.0-SNAPSHOT/maven-plugin-usage-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/pom.xml to org.jboss.windup.jenkins/windup-core-dependents-aggregate-pom/2.3.0-SNAPSHOT/windup-core-dependents-aggregate-pom-2.3.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/pom.xml to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/pom.xml to org.jboss.windup.quickstarts/windup-quickstarts-root/2.5.0-SNAPSHOT/windup-quickstarts-root-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/pom.xml to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/classes/META-INF/resources/windup-victims-2.5.0-SNAPSHOT.dot to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT-forge-addon.jarchannel stoppedArchiving artifactsIRC notifier plugin: Sending notification to: #windupSetting status of 30ca784742dbacad9c8bcf85e138b339ab41a1eb to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/766/ and message: 'Build finished. 5 tests run, 0 skipped, 0 failed.'

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1394/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/796/

**Comment by jsight** [comment]
Probably not really the right way to do this... needs a rethink.

**Pull request closed without merging**
