### PR TITLE
WINDUP-895, WINDUP-905 enhanced jquery.tablesorter with child rows hi…

### PR DESCRIPTION
**Pull request by mareknovotny**
…ding

Fixing both issues
https://issues.jboss.org/browse/WINDUP-895
https://issues.jboss.org/browse/WINDUP-905

### CODE REVIEW

**Comment by mareknovotny** [comment]
Showing screenshot for the changed Migration Issues Report
screenshot from 2016-02-11 14-38-26

The whole app reports are shared through gdrive

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1450/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/828/<h2>Build result: FAILURE</span></h2>[...truncated 68362 lines...][JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/maven-plugin-usage/pom.xml to org.jboss.windup.quickstarts/maven-plugin-usage/2.5.0-SNAPSHOT/maven-plugin-usage-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/maven-plugin-usage/target/maven-plugin-usage-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/maven-plugin-usage/2.5.0-SNAPSHOT/maven-plugin-usage-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/maven-plugin-usage/target/maven-plugin-usage-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.quickstarts/maven-plugin-usage/2.5.0-SNAPSHOT/maven-plugin-usage-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/pom.xml to org.jboss.windup.jenkins/windup-core-dependents-aggregate-pom/2.3.0-SNAPSHOT/windup-core-dependents-aggregate-pom-2.3.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/pom.xml to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/pom.xml to org.jboss.windup.quickstarts/windup-quickstarts-root/2.5.0-SNAPSHOT/windup-quickstarts-root-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/pom.xml to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/classes/META-INF/resources/windup-victims-2.5.0-SNAPSHOT.dot to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT-forge-addon.jarchannel stoppedArchiving artifactsIRC notifier plugin: Sending notification to: #windupSetting status of f556eaaf56807cf1e3596d38c07df3c8d5a4a461 to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/828/ and message: 'Build finished. 5 tests run, 0 skipped, 0 failed.'

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/829/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1451/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1452/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/830/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/831/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1453/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1454/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/832/

**Comment by jsight** [comment]
The incident count section looks really weird to me now (the descriptions are too far from the data itself):
http://i.imgur.com/9PKUfL8.png

Also, ruleSummary.ruleID is nullable, so this report crashes in some cases as migration-issues assumes that it can't be null. I also feel like the rule id link should be less prominent as that has been complained about in the past.

Those are pretty small issues, though. Maybe we can demo this on Monday and see if the design is close enough to what people want otherwise?

**Comment by rdruss** [comment]
I agree on both points Jess.  Maybe show the report layout (old and new) at the standup on Monday?

**Comment by mareknovotny** [comment]
> The incident count section looks really weird to me now (the descriptions are too far from the 
 data itself): http://i.imgur.com/9PKUfL8.png

WINDUP-905 is also about aligning of all number values in tables to right. The original content of the table cell was as can be seen here 
screenshot from 2016-02-15 09-49-01
and if you resize browser window it gets worst by wrapping on more lines. Look here 
screenshot from 2016-02-15 09-49-11

So moving text to right too is like this
screenshot from 2016-02-15 10-13-35
or resized as this 
screenshot from 2016-02-15 10-13-41


> Also, ruleSummary.ruleID is nullable, so this report crashes in some cases as migration-issues assumes that it can't be null. 

I think my commit uses `${problemSummary.ruleID}` and that should be not null? not sure ;). I thought that ruleSummary.ruleID is the key, but if that ruleID is not filled it won't create problemSummary at all or am I missing something? 

>I also feel like the rule id link should be less prominent as that has been complained about in the past.

I tried to create what is on Spreadsheet Mock Up from Tobias. If we need to replace text with icon or use smaller font, I am not against it, but the current look was wanted I guess.

**Comment by jsight** [comment]
@mareknovotny - It shouldn't be null, but it sometimes is. It looks like the schema validator rule has a bug. Nevertheless, it would be better if the page didn't crash in that case. :)

**Comment by jsight** [comment]
Just marking it until you upload your latest changes.

**Pull request merged**
