### PR TITLE
Fighting the Out of memory exception 1.commit

### PR DESCRIPTION
**Pull request by mbriskar**
All the field information that remains after the operation runs will stay stored throughout the whole windup execution. This is a simple fix and may have bigger impact, however the biggest problem still remains the graph database. The first point in the https://gist.github.com/mbriskar/3f2e4f502e68ad614fdd documentation of issue

### CODE REVIEW

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
Good catch... I can see that this would never get garbage collected otherwise.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/620/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1246/

**Pull request merged**
