### PR TITLE
WINDUP-856 adding label legend to technology related tags

### PR DESCRIPTION
**Pull request by mareknovotny**
A proposal for how to show Label color legend from technology tag level information

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/684/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1311/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='windup-pr-builder/org.jboss.windup.rexster:windup-rexster-tests' /><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1311/org.jboss.windup.rexster$windup-rexster-tests/testReport'>windup-pr-builder/org.jboss.windup.rexster:windup-rexster-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1311/org.jboss.windup.rexster$windup-rexster-tests/testReport/org.jboss.windup.graph.rexster.test.debug/RexsterDefaultDeploymentDebugTest/testRexsterProperStart/'><strong>org.jboss.windup.graph.rexster.test.debug.RexsterDefaultDeploymentDebugTest.testRexsterProperStart</strong></a></li></ul>

**Comment by mareknovotny** [comment]
@windupgithubbot1 retest

**Comment by mbriskar** [comment]
I feel it would be better to not have this legend fixed because that information is not that important and user will need to check it maybe only once. My suggestion would probably be to show that pop-up only if a person hover over the table header.

screenshot from 2015-12-17 14-44-08

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/688/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1315/

**Comment by mareknovotny** [comment]
@jsight , @mbriskar ok, I will change it to Technology table column headding if that looks better.

**Comment by mareknovotny** [comment]
I added an update to technology tag label legend. If you still don't like this aproach there is https://github.com/windup/windup/pull/800 which is the same but without tag label legend

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1321/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/695/

**Comment by jsight** [comment]
@rdruss I think that I prefer it without the legend, but I'm not sure. Can you take a look?

**Comment by mareknovotny** [comment]
@rdruss here is the live preview http://file.rdu.redhat.com/~mnovotny/public.report/

**Comment by jsight** [comment]
Closing (merged https://github.com/windup/windup/pull/800 instead)

**Pull request closed without merging**
