### PR TITLE
WINDUP-846: Windup bootstrap runs slow even for showing help usage

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-846

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/626/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1252/

**Comment by mareknovotny** [comment]
I like the result, it now run less than 1 second!

I didn't notice that there is a windup bash completion, we need a documentation of the install/usage I guess. But that could be worked on in https://issues.jboss.org/browse/WINDUP-851.

**Comment by jsight** [comment]
@mareknovotny - Yes, we have one. We haven't documented it as it is still sort of experimental. Lincoln had reported that it didn't work on the Mac at all, and there were some known issues on Linux as well (mainly the slow synchronous initial load before). It's probably worth revisiting now that we generate the data during the build.

**Comment by jsight** [comment]
@mareknovotny Also, thanks for the review/merge. :)

**Pull request merged**
