### PR TITLE
Fixed an issue with path selection during decompilation. Also, made the unbound references scanning functionality optional

### PR DESCRIPTION
**Pull request by jsight**
This also makes "target" a required parameter.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/368/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/997/<h2>Failed Tests: <span class='status-failure'>11</span></h2><h3><a name='org.jboss.windup.ui:windup-ui-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport'>org.jboss.windup.ui:windup-ui-tests</a>: <span class='status-failure'>11</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandRuleFilteringTest/testRuleFilteringIncludeTag2/'><strong>org.jboss.windup.addon.ui.WindupCommandRuleFilteringTest.testRuleFilteringIncludeTag2</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandRuleFilteringTest/testRuleFilteringExcludeTag3/'><strong>org.jboss.windup.addon.ui.WindupCommandRuleFilteringTest.testRuleFilteringExcludeTag3</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandRuleFilteringTest/testRuleFilteringSourceGlassfishTargetJBoss/'><strong>org.jboss.windup.addon.ui.WindupCommandRuleFilteringTest.testRuleFilteringSourceGlassfishTargetJBoss</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandRuleFilteringTest/testRuleFilteringSourceGlassfish/'><strong>org.jboss.windup.addon.ui.WindupCommandRuleFilteringTest.testRuleFilteringSourceGlassfish</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testOverwriteConfirmation/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testOverwriteConfirmation</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testUserRulesDirMigration/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testUserRulesDirMigration</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testDuplicateUserRulesDirMigration/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testDuplicateUserRulesDirMigration</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testNewMigration/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testNewMigration</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testUserIgnoreDirMigration/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testUserIgnoreDirMigration</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testOutputDirCannotBeParentOfInputDir/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testOutputDirCannotBeParentOfInputDir</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/997/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testOutputDefaultValue/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testOutputDefaultValue</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/369/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/998/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/370/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/999/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/371/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1000/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/372/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1001/
Test PASSed.

**Comment by mbriskar** [comment]
I think this looks good and it may be good to go for now. I was thinking about this issue and I thought it could be connected with the future plan to "disable rules from happening" in https://issues.jboss.org/browse/WINDUP-716. Maybe it could be possible to have some global file that would gather rule IDs that are disabled from happening. Class not found could be then put there by default. The information contained in this file could be accessible through report, so people could re-enable some rules from happening... Just an idea, what do you think?

**Comment by lincolnthree** [comment]
Looks good to me!

**Comment by mbriskar** [comment]
@lincolnthree didn't you overlook my comment?

**Comment by jsight** [comment]
@mbriskar - I do agree that some of this could be in a more general feature. But I don't think that it's generally a great user experience to require the user to edit a file in order to change runtime options like this. Basically, I think we need both.

Also, the --target stuff needs to be improved to help the user if they don't specify it. I'll work on that next.

**Comment by mbriskar** [comment]
@jsight maybe you are right. However I feel this will be a way to go when windup will run in web app, where there would be a place where user would be able to enable/disable rules from happening

**Comment by jsight** [comment]
@mbriskar Yes, we'll want a nice interface for doing that at some point.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/375/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1004/
Test PASSed.

**Comment by mbriskar** [comment]
@jsight  however my point was more that even though there would be still the same console option, internally it could be implemented with some file gathering of these rule ids that should be ignored. Then we would reuse this in the future for WINDUP-716

**Comment by mbriskar** [comment]
and it would give us an opportunity to react to problems really fast just by disabling rule that cause problems.. The more I think about it, the more I am it looks more promising

**Comment by jsight** [comment]
@mbriskar There is more to this particular change than just disabling one rule.

**Comment by mbriskar** [comment]
@jsight Ok, then in that case I am speaking just about disabling that unbound references

**Pull request merged**
