### PR TITLE
WINDUP-863 - Made the static IP Address scanner take into considerati…

### PR DESCRIPTION
**Pull request by bradsdavis**
…on commented out properties and Maven version numbers.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1269/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/643/

**Comment by bradsdavis** [comment]
@jsight When this was merged, the isMavenVersionTag method was removed and it is dead code right now.  However, I think it should still be included in the code.  

Specifically, you may have this XML: 

```
<version>
1.3.5.6
</version>
```

That would not be caught in the ignoreLine method alone because version is not on the same line as the 1.3.5.6 value -- since it is XML.  I think this is very likely going to be encountered in Maven files, which is why I handle Maven differently than property files.

**Comment by jsight** [comment]
@bradsdavis - Good point... I'll merge a fix. Thanks for the contribution!

**Pull request merged**
