### PR TITLE
Use freemarker updates

### PR DESCRIPTION
**Pull request by OndraZizka**
Seems to work fine. I didn't check all reports but no errors were thrown with sample app.

### CODE REVIEW

**Comment by mareknovotny** [comment]
it seems your changes in templates broke HTMLUnit tests which relies on some xpaths.

**Comment by OndraZizka** [comment]
OK I'll check that

**Comment by OndraZizka** [comment]
If someone has a moment to have a look at this before I do, It would be appreciated.

**Comment by OndraZizka** [comment]
WARNING: Failed to render freemarker report:
    [v[39424]={templateType: FREEMARKER, w:winduptype: [ApplicationReportModel, ReportModel], reportName: Compatible Files, reportFilename: compatiblefiles_catchalltest.html, mainApplicationModel: false, reportPriority: 200, reportDescription: This provides a list of files that are believed to be compatible, potentially requiring no migration effort., reportIconClass: glyphicon glyphicon-check, templatePath: /reports/templates/compatible_files.ftl, displayInApplicationReportIndex: true}]
freemarker.template.DefaultIterableAdapter cannot be cast to freemarker.ext.beans.StringModel
java.lang.ClassCastException: freemarker.template.DefaultIterableAdapter cannot be cast to freemarker.ext.beans.StringModel
        at org.jboss.windup.rules.apps.java.reporting.freemarker.FindFilesNotClassifiedOrHinted.exec(FindFilesNotClassifiedOrHinted.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by OndraZizka** [comment]
Oct 15, 2017 3:26:09 AM org.jboss.windup.reporting.rules.rendering.RenderReportRuleProvider$FreeMarkerThreadedRenderer$1 call
WARNING: Failed to render freemarker report:
    [v[38912]={templateType: FREEMARKER, w:winduptype: [JavaApplicationOverviewReportModel, ApplicationReportModel, ReportModel], reportName: Application Details, reportFilename: ApplicationDetails_catchalltest.html, mainApplicationModel: false, reportPriority: 102, reportDescription: An exhaustive list of all of the information and issues found within the application., reportIconClass: glyphicon glyphicon-th-list, templatePath: /reports/templates/java_application.ftl, excludeTags:catchall: 1, displayInApplicationReportIndex: true}]
Unrecognized type passed to: iterableHasContent: freemarker.template.DefaultIterableAdapter
org.jboss.windup.util.exception.WindupException: Unrecognized type passed to: iterableHasContent: freemarker.template.DefaultIterableAdapter
        at org.jboss.windup.rules.apps.java.reporting.freemarker.IterableHasContent.hasContent(IterableHasContent.java:71)
        at org.jboss.windup.rules.apps.java.reporting.freemarker.IterableHasContent.exec(IterableHasContent.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by OndraZizka** [comment]
retest

**Pull request merged**
