### PR TITLE
Fix broken link to JBoss EAP JavaDocs

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
@windupgithubbot1 retest

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by lincolnthree** [comment]
Thanks Sande!

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test PASSed.

**Comment by windupgithubbot1** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/380/
Test PASSed.

**Pull request merged**
