### PR TITLE
Decompile filtering

### PR DESCRIPTION
**Pull request by bradsdavis**
Filters an archive's entries based on the --packages parameter.

### CODE REVIEW

**Comment by bradsdavis** [comment]
Even though there is the ShouldDecompileCriterion, that will only tell you whether the JAR includes a package that is relevant to decompile, and thus if the JAR needs to be decompiled.  However, there is the situation (like super JARs) where there are both relevant and non-relevant classes in a JAR.  This filter skips non-relevant Java classes from decompiling from the archive.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/692/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/63/
Test PASSed.

**Comment by jsight** [comment]
Continued in https://github.com/windup/windup/pull/536

**Pull request closed without merging**
