### PR TITLE
WINDUP-448: Support the parameterization of xpath (XmlFile) rules

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-448

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/354/<h2>Failed Tests: <span class='status-failure'>7</span></h2><h3><a name='org.jboss.windup.config:windup-config-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.config$windup-config-tests/testReport'>org.jboss.windup.config:windup-config-tests</a>: <span class='status-failure'>4</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/testIterationVariableResolving/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.testIterationVariableResolving</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/testIterationVariableResolving2/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.testIterationVariableResolving2</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/testIterationVariableResolving3/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.testIterationVariableResolving3</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/testIterationVariableResolving4/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.testIterationVariableResolving4</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-java' /><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.rules.apps$rules-java/testReport'>org.jboss.windup.rules.apps:rules-java</a>: <span class='status-failure'>3</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/JavaClassCompositeTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassCompositeTest.testJavaClassCondition</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/JavaClassTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassTest.testJavaClassCondition</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/354/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/JavaClassXmlRulesTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassXmlRulesTest.testJavaClassCondition</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/355/<h2>Failed Tests: <span class='status-failure'>7</span></h2><h3><a name='org.jboss.windup.config:windup-config-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.config$windup-config-tests/testReport'>org.jboss.windup.config:windup-config-tests</a>: <span class='status-failure'>4</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/testIterationVariableResolving/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.testIterationVariableResolving</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/testIterationVariableResolving2/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.testIterationVariableResolving2</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/testIterationVariableResolving3/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.testIterationVariableResolving3</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/testIterationVariableResolving4/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.testIterationVariableResolving4</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-java' /><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.rules.apps$rules-java/testReport'>org.jboss.windup.rules.apps:rules-java</a>: <span class='status-failure'>3</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/JavaClassCompositeTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassCompositeTest.testJavaClassCondition</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/JavaClassTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassTest.testJavaClassCondition</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/355/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/JavaClassXmlRulesTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassXmlRulesTest.testJavaClassCondition</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/356/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='org.jboss.windup.rules.apps:rules-java-ee' /><a href='https://10.3.9.192/job/windup-pr-builder/356/org.jboss.windup.rules.apps$rules-java-ee/testReport'>org.jboss.windup.rules.apps:rules-java-ee</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/356/org.jboss.windup.rules.apps$rules-java-ee/testReport/org.jboss.windup.rules.apps.javaee.tests/XmlJonasConfigTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.apps.javaee.tests.XmlJonasConfigTest.testHintsAndClassificationOperation</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:rules-xml' /><a href='https://10.3.9.192/job/windup-pr-builder/356/org.jboss.windup.rules.apps$rules-xml/testReport'>org.jboss.windup.rules.apps:rules-xml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/356/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml/XMLTransformationTest/testXSLTTransformation/'><strong>org.jboss.windup.rules.xml.XMLTransformationTest.testXSLTTransformation</strong></a></li></ul><h3><a name='org.jboss.windup.tests:tests' /><a href='https://10.3.9.192/job/windup-pr-builder/356/org.jboss.windup.tests$tests/testReport'>org.jboss.windup.tests:tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/356/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSpringSmallTest/testRunWindupSmallSpringApp/'><strong>org.jboss.windup.tests.application.WindupArchitectureSpringSmallTest.testRunWindupSmallSpringApp</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/357/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup.rules:rules-java-project' /><a href='https://10.3.9.192/job/windup-pr-builder/357/org.jboss.windup.rules$rules-java-project/testReport'>org.jboss.windup.rules:rules-java-project</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/357/org.jboss.windup.rules$rules-java-project/testReport/org.jboss.windup.project.operation.test.handlers/LineHandlerTest/testLineItemWithMessage/'><strong>org.jboss.windup.project.operation.test.handlers.LineHandlerTest.testLineItemWithMessage</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/357/org.jboss.windup.rules$rules-java-project/testReport/org.jboss.windup.project.operation.test.handlers/LineHandlerTest/testLineItemWithoutMessage/'><strong>org.jboss.windup.project.operation.test.handlers.LineHandlerTest.testLineItemWithoutMessage</strong></a></li></ul>
Test FAILed.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/358/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.reporting:windup-reporting-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/358/org.jboss.windup.reporting$windup-reporting-tests/testReport'>org.jboss.windup.reporting:windup-reporting-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/358/org.jboss.windup.reporting$windup-reporting-tests/testReport/org.jboss.windup.reporting/FreeMarkerIterationOperationTest/testApplicationReportFreemarker/'><strong>org.jboss.windup.reporting.FreeMarkerIterationOperationTest.testApplicationReportFreemarker</strong></a></li></ul>
Test FAILed.

**Pull request merged**
