### PR TITLE
WINDUP-592 WIP

### PR DESCRIPTION
**Pull request by OndraZizka**
Failed to get instance of [class org.jboss.windup.rules.apps.java.config.CopyJavaConfigToGraphRuleProvider] with proxy for ClassLoader [ModuleClassLoader for Module "org.jboss.windup.rules.apps.windup-rules-java:2.3.0-SNAPSHOT_17180833-8b26-4b31-85f6-1e8a84f6be61" from AddonModuleLoader]
	at org.jboss.forge.furnace.container.cdi.impl.ImportedBeanLifecycle.create(ImportedBeanLifecycle.java:121)

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/118/<h2>Failed Tests: <span class='status-failure'>4</span></h2><h3><a name='org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/118/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport'>org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/118/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport/org.jboss.windup.qs.rules/EjbBeanUtilsAsyncUsageRuleProviderTest/testRules/'><strong>org.jboss.windup.qs.rules.EjbBeanUtilsAsyncUsageRuleProviderTest.testRules</strong></a></li></ul><h3><a name='org.jboss.windup.quickstarts:windup-victims' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/118/org.jboss.windup.quickstarts$windup-victims/testReport'>org.jboss.windup.quickstarts:windup-victims</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/118/org.jboss.windup.quickstarts$windup-victims/testReport/org.jboss.windup.qs.victims.test/VictimsRulesetTest/testAffectedJarsFound/'><strong>org.jboss.windup.qs.victims.test.VictimsRulesetTest.testAffectedJarsFound</strong></a></li></ul><h3><a name='org.jboss.windup.quickstarts:windup-weblogic-javaee-servlet-rules-java' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/118/org.jboss.windup.quickstarts$windup-weblogic-javaee-servlet-rules-java/testReport'>org.jboss.windup.quickstarts:windup-weblogic-javaee-servlet-rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/118/org.jboss.windup.quickstarts$windup-weblogic-javaee-servlet-rules-java/testReport/org.jboss.windup.qs.rules/MyJavaHintsTest/testJavaHints/'><strong>org.jboss.windup.qs.rules.MyJavaHintsTest.testJavaHints</strong></a></li></ul><h3><a name='org.jboss.windup.rules:windup-rulesets' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/118/org.jboss.windup.rules$windup-rulesets/testReport'>org.jboss.windup.rules:windup-rulesets</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/118/org.jboss.windup.rules$windup-rulesets/testReport/org.jboss.windup.rules.tests/WindupRulesTest/testWindupRules/'><strong>org.jboss.windup.rules.tests.WindupRulesTest.testWindupRules</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/750/<h2>Failed Tests: <span class='status-failure'>47</span></h2><h3><a name='org.jboss.windup:windup-tooling-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup$windup-tooling-tests/testReport'>org.jboss.windup:windup-tooling-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup$windup-tooling-tests/testReport/org.jboss.windup.tooling/ExecutionBuilderTest/testExecutionBuilder/'><strong>org.jboss.windup.tooling.ExecutionBuilderTest.testExecutionBuilder</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-base-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-base-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-base-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-base-tests/testReport/org.jboss.windup.rules.apps.condition/FileContentTest/testFileContentScan/'><strong>org.jboss.windup.rules.apps.condition.FileContentTest.testFileContentScan</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-archives-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-archives-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-archives-tests</a>: <span class='status-failure'>2</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-archives-tests/testReport/org.jboss.windup.rules.apps.java.archives/IdentifyArchivesRulesetTest/testJarsAreIdentified/'><strong>org.jboss.windup.rules.apps.java.archives.IdentifyArchivesRulesetTest.testJarsAreIdentified</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-archives-tests/testReport/org.jboss.windup.rules.apps.java.archives/IgnoreArchivesRulesetTest/testSkippedArchivesFound/'><strong>org.jboss.windup.rules.apps.java.archives.IgnoreArchivesRulesetTest.testSkippedArchivesFound</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-ee-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-ee-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport/org.jboss.windup.rules.apps.javaee.tests/DiscoverEjbConfigurationTest/testEJBMetadataExtraction/'><strong>org.jboss.windup.rules.apps.javaee.tests.DiscoverEjbConfigurationTest.testEJBMetadataExtraction</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-project-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-project-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-project-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-project-tests/testReport/org.jboss.windup.project.operation.test/OverviewReportLineTest/testHintAndClassificationOperation/'><strong>org.jboss.windup.project.operation.test.OverviewReportLineTest.testHintAndClassificationOperation</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-tests</a>: <span class='status-failure'>12</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rule.groovy/GroovyExtensionJavaRulesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rule.groovy.GroovyExtensionJavaRulesTest.testHintsAndClassificationOperation</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.apps.java.scan.ast/ASTProcessorIntegrationTest/testJavaSourceScanning/'><strong>org.jboss.windup.rules.apps.java.scan.ast.ASTProcessorIntegrationTest.testJavaSourceScanning</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/GatherIgnoredFilesTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.GatherIgnoredFilesTest.testJavaClassCondition</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/JavaClassCompositeTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassCompositeTest.testJavaClassCondition</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/JavaClassSourceMatchTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassSourceMatchTest.testJavaClassCondition</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/JavaClassTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassTest.testJavaClassCondition</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/JavaClassXmlRulesTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.JavaClassXmlRulesTest.testJavaClassCondition</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/JavaHintsClassificationsTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.java.JavaHintsClassificationsTest.testHintsAndClassificationOperation</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/SourceModeTest/testSourceModeDefault/'><strong>org.jboss.windup.rules.java.SourceModeTest.testSourceModeDefault</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/SourceModeTest/testSourceModePositive/'><strong>org.jboss.windup.rules.java.SourceModeTest.testSourceModePositive</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java/SourceModeTest/testSourceModeNegative/'><strong>org.jboss.windup.rules.java.SourceModeTest.testSourceModeNegative</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.java.ignore/JavaIgnoreRegexesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.java.ignore.JavaIgnoreRegexesTest.testHintsAndClassificationOperation</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-xml-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-xml-tests</a>: <span class='status-failure'>10</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.apps.xml.groovy/GroovyExtensionXmlRulesTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.apps.xml.groovy.GroovyExtensionXmlRulesTest.testHintsAndClassificationOperation</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XMLFileNestedConditionTest/testNestedCondition/'><strong>org.jboss.windup.rules.xml.XMLFileNestedConditionTest.testNestedCondition</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XMLHintsClassificationsTest/testHintAndClassificationOperation/'><strong>org.jboss.windup.rules.xml.XMLHintsClassificationsTest.testHintAndClassificationOperation</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XMLTransformationTest/testXSLTTransformation/'><strong>org.jboss.windup.rules.xml.XMLTransformationTest.testXSLTTransformation</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XMLTransformationXMLRulesTest/testXSLTTransformation/'><strong>org.jboss.windup.rules.xml.XMLTransformationXMLRulesTest.testXSLTTransformation</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XmlAndJavaParameterizedTest/testXmlAndJavaSearchParams/'><strong>org.jboss.windup.rules.xml.XmlAndJavaParameterizedTest.testXmlAndJavaSearchParams</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XmlFileMultipleConditionTest/testNestedCondition/'><strong>org.jboss.windup.rules.xml.XmlFileMultipleConditionTest.testNestedCondition</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParams/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParams</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParamsDangling/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParamsDangling</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParamsMultiCondition/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParamsMultiCondition</strong></a></li></ul><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>12</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/MavenInfoMissingBinaryModeTest/testRunMavenInfoMissing/'><strong>org.jboss.windup.tests.application.MavenInfoMissingBinaryModeTest.testRunMavenInfoMissing</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureHibernateTest/testRunWindupHibernate/'><strong>org.jboss.windup.tests.application.WindupArchitectureHibernateTest.testRunWindupHibernate</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureScanPackagesTest/testRunWindupScanPackages/'><strong>org.jboss.windup.tests.application.WindupArchitectureScanPackagesTest.testRunWindupScanPackages</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryMode2Test/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryMode2Test.testRunWindupTiny</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryModeTest/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryModeTest.testRunWindupTiny</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSoa5GatewaysRoutersTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSoa5GatewaysRoutersTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceWithBadPOMTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceWithBadPOMTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSpringSmallTest/testRunWindupSmallSpringApp/'><strong>org.jboss.windup.tests.application.WindupArchitectureSpringSmallTest.testRunWindupSmallSpringApp</strong></a></li></ul><h3><a name='org.jboss.windup.ui:windup-ui-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.ui$windup-ui-tests/testReport'>org.jboss.windup.ui:windup-ui-tests</a>: <span class='status-failure'>7</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testOverwriteConfirmation/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testOverwriteConfirmation</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testUserRulesDirMigration/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testUserRulesDirMigration</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testDuplicateUserRulesDirMigration/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testDuplicateUserRulesDirMigration</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testNewMigration/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testNewMigration</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testUserIgnoreDirMigration/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testUserIgnoreDirMigration</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testOutputDirCannotBeParentOfInputDir/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testOutputDirCannotBeParentOfInputDir</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/750/org.jboss.windup.ui$windup-ui-tests/testReport/org.jboss.windup.addon.ui/WindupCommandTest/testOutputDefaultValue/'><strong>org.jboss.windup.addon.ui.WindupCommandTest.testOutputDefaultValue</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/119/
Test PASSed.

**Comment by OndraZizka** [comment]
Agreed to put this func to WindupCommand.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/751/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/120/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/752/
Test PASSed.

**Pull request closed without merging**
