### PR TITLE
Fixing (X)HTML markup

### PR DESCRIPTION
**Pull request by Maarc**
This is a fix for having more XHTML compliant reports.
With this fix it is for example possible to process and merge the summary files using xmllint.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by mareknovotny** [comment]
it seems ok to me. Thanks @Maarc !

**Comment by jsight** [comment]
Thanks @Maarc

**Pull request merged**
