### PR TITLE
Mbriskar windup 667

### PR DESCRIPTION
**Pull request by jsight**
Continuation of: 
https://github.com/windup/windup/pull/615

### CODE REVIEW

**Comment by jsight** [comment]
@mbriskar Could you look this over? I've tweaked a few things, as it seemed like it was possible for FileContent to return too many results before.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/254/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/885/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/255/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/886/
Test PASSed.

**Pull request merged**
