### PR TITLE
WINDUP-773: Fix the appearance of duplicate services in the remote services report

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-773

### CODE REVIEW

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/415/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1044/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/416/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1045/
Test PASSed.

**Comment by mbriskar** [comment]
It looks good, especially with all the tests for the services, however I cannot find the actual fix. What caused the duplicates?

**Comment by jsight** [comment]
@mbriskar This patch adds services that look for an existing remote service before creating a new entry. Effectively it is just doing duplicate detection for remote services during discovery.

I think that we occasionally find duplicate EJBs in cases where the EJB is defined in multiple places. This could happen if they include the same EJB in multiple jars (it happens).

**Pull request merged**
