### PR TITLE
Fixing HTML/CSS markup (rounded corners and added padding)

### PR DESCRIPTION
**Pull request by Maarc**
Added a radius on "table-bordered" to make sure that striped tables having a grey last row look nice.

Fixed padding issue on the main java_application page.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
@windupgithubbot1 retest

**Comment by jsight** [comment]
Thanks @Maarc!

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/434/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1063/
Test FAILed.

**Comment by jsight** [comment]
retest

**Pull request merged**
