### PR TITLE
WINDUP-953 Generate Jandex indices to speed up Furnace bootstrap

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
Is there any indication of how much of a difference this made?

**Comment by mkouba** [comment]
No exact numbers. And I would guess it won't be that significant. But AFAIK this it what Forge guys did to improve the bootstrap and it made Weld classes disappear from the list of hot spots.

**Comment by jsight** [comment]
@mkouba I tested it a few times and could not see a single second of improvement when running against jee-example.

It makes me wonder if it is actually working?

**Comment by mkouba** [comment]
It should work according to the log. I will try to do some tests...

**Comment by mkouba** [comment]
I cannot see any improvement neither. Actually, Weld SE is using Jandex even if there is no index available (it's created on the fly). Also Jandex only helps to filter out classes which should not end up as managed beans and to filter `ProcessAnnotatedType` observers with `@WithAnnotations` specified (and unfortunately neither is the case of Forge/Windup).

I'm going to close this pull request and corresponding JIRA as we're not observing any improment.

**Pull request closed without merging**
