### PR TITLE
WINDUP-2032 Sorting by aggregated columns within a tier

### PR DESCRIPTION
**Pull request by m-brophy**
https://issues.redhat.com/browse/WINDUP-2032

### CODE REVIEW

**Comment by m-brophy** [comment]
retest

**Comment by carlosthe19916** [comment]
@m-brophy Is this PR still valid? or this ticket will be solved on another ticket? I've just tested this PR and it seems that there are still problems when sorting using the last 3 columns. It does not work (see the screenshot below).

Screenshot from 2019-11-11 11-54-03

**Comment by carlosthe19916** [comment]
> @m-brophy Is this PR still valid? or this ticket will be solved on another ticket? I've just tested this PR and it seems that there are still problems when sorting using the last 3 columns. It does not work (see the screenshot below).
> 
> Static analysis: [adit-arendus-1.1.24.ear.report.zip](https://github.com/windup/windup/files/3830998/adit-arendus-1.1.24.ear.report.zip)
> 
> Screenshot from 2019-11-11 11-54-03

Answer to myself: This problem is fixed in another PR https://github.com/windup/windup/pull/1361. So, no need to do something else, this PR looks good to me

**Comment by m-brophy** [comment]
There's also this PR https://github.com/windup/windup/pull/1346 
which was merged in April for the same JIRA  - it's a problem that the same JIRA has been used for multiple different PRs but they haven't all beenreferenced on the JIRA

**Comment by m-brophy** [comment]
@carlosthe19916 do you think this PR can be closed without merging as redundant?

**Comment by carlosthe19916** [comment]
> @carlosthe19916 do you think this PR can be closed without merging as redundant?

Sorry for the confusion @m-brophy I think this PR is still valid. I think both https://github.com/windup/windup/pull/1361 and the current PR should be merged.

**Pull request merged**
