### PR TITLE
WINDUP-746 hint title should be mandatory in Windup schema

### PR DESCRIPTION
**Pull request by mareknovotny**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
test this please

**Comment by jsight** [comment]
Great job... thanks @mareknovotny!

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1038/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/410/
Test PASSed.

**Pull request merged**
