### PR TITLE
Rename rule-schema to append version number _1_0

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
Someone requested version 1.0, but I thought they were requesting the change to the xml declaration itself?

**Comment by mareknovotny** [comment]
@jsight  is true I was asking why it is 1.1 in xml declaration attribute

**Comment by sgilda** [comment]
@jsight , @mareknovotny : Should I close this pull?

**Comment by mareknovotny** [comment]
@sgilda I think so. this change is not wanted

**Comment by sgilda** [comment]
@jsight and @mareknovotny : I just realized, the change you are talking about is in this pull: https://github.com/windup/windup/pull/561

It has not yet been merged.

**Comment by lincolnthree** [comment]
Closing this as we decided to do something else.

**Pull request closed without merging**
