### PR TITLE
WINDUP-1325 Force US locale for non-US environments

### PR DESCRIPTION
**Pull request by juangon**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
@windupgithubbot1 test this please

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by mareknovotny** [comment]
retest

**Comment by mareknovotny** [comment]
retest

**Comment by juangon** [comment]
retest

**Comment by mareknovotny** [comment]
you don't have the power to trigger new test build ;)

**Comment by mareknovotny** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Pull request merged**
