### PR TITLE
WINDUP-570: Add ability to set ConfigurationOption values to Windup T…

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-570

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/223/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/855/
Test FAILed.

**Comment by lincolnthree** [comment]
Looks good. But it doesn't appear to compile. Did you miss an @Override or add an extra one?

**Comment by jsight** [comment]
I think I pushed a fix for that? I had removed an api from the interface
but not the implementation.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/225/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/225/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport'>org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/225/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport/org.jboss.windup.qs.rules/EjbBeanUtilsAsyncUsageRuleProviderTest/testRules/'><strong>org.jboss.windup.qs.rules.EjbBeanUtilsAsyncUsageRuleProviderTest.testRules</strong></a></li></ul>
Test FAILed.

**Comment by lincolnthree** [comment]
test this please

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/857/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/857/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/857/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/227/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/227/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport'>org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/227/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport/org.jboss.windup.qs.rules/EjbBeanUtilsAsyncUsageRuleProviderTest/testRules/'><strong>org.jboss.windup.qs.rules.EjbBeanUtilsAsyncUsageRuleProviderTest.testRules</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/859/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/859/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/859/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li></ul>
Test FAILed.

**Comment by jsight** [comment]
retest

**Comment by lincolnthree** [comment]
Merged.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/860/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/228/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/228/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport'>org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/228/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport/org.jboss.windup.qs.rules/EjbBeanUtilsAsyncUsageRuleProviderTest/testRules/'><strong>org.jboss.windup.qs.rules.EjbBeanUtilsAsyncUsageRuleProviderTest.testRules</strong></a></li></ul>
Test FAILed.

**Pull request closed without merging**
