### PR TITLE
Some fixes to JavaClass and XmlFile that were found during the testing of a quickstart

### PR DESCRIPTION
**Pull request by jsight**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/538/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='org.jboss.windup.rules.apps:windup-rules-xml-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/538/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-xml-tests</a>: <span class='status-failure'>3</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/538/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParams/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParams</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/538/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParamsDangling/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParamsDangling</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/538/org.jboss.windup.rules.apps$windup-rules-xml-tests/testReport/org.jboss.windup.rules.xml/XmlFileParameterizedTest/testXmlParamsMultiCondition/'><strong>org.jboss.windup.rules.xml.XmlFileParameterizedTest.testXmlParamsMultiCondition</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/541/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/542/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/543/
Test PASSed.

**Comment by lincolnthree** [comment]
Nice test.

**Pull request merged**
