### PR TITLE
Rework the application details report to work with the latest changes…

### PR DESCRIPTION
**Pull request by jsight**
… to the deduplication process.

Reference: https://docs.google.com/document/d/1L8ztKgg5t33VTnt1xiisDZlavYX8ozQyo0xqVSk1a9Y/edit

### CODE REVIEW

**Comment by jsight** [comment]
Needs tweaks to report_index... this page should display numbers based on only deduplication within the single application.

**Comment by jsight** [comment]
I think this gets report_index back to a more logical state.

**Comment by OndraZizka** [comment]
It looks good and logical.
Could you please put a description of what each traversal mode is meant for? I mean, the typical use cases for them. Or is it in the codebase already?

**Comment by mareknovotny** [comment]
http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/org.jboss.windup.tests$windup-tests/1680/testReport/junit/org.jboss.windup.tests.application/WindupArchitectureDuplicateTest/testRunWindupDuplicateEAR/ failed

**Comment by mareknovotny** [comment]
not sure if this is a bug or I am thinking in wrong way, but I copied 
jee-example-app-1.0.0.ear as copy.ear, I would expext that 
copy.ear/jee-example-web.war and 
jee-example-app-1.0.0.ear/jee-example-web.war will be marked as shared/duplicated archives. But they are not.

**Comment by jsight** [comment]
@OndraZizka https://docs.google.com/document/d/1wIq8Qylvd1PS_A49jFEeCht7kC0UAPmUyxwJOaUEfUE/edit# - Feel free to add notes as well. I added a few notes to the javadoc, but I'm not sure that there is much else to add there.

@mareknovotny - I'm not sure that I understand what you mean? They do show up in the shared-libs app for me? They do not show up as [shared] within the individual application's report as they are not "shared" within the context of that report. Basically things are only marked "shared" there if they are shared within the context of the current application.

**Comment by mareknovotny** [comment]
> They do show up in the shared-libs app for me? 
Hmm, I can see it in all applications -> copy.ear, jee-example-app-1.0.0.ear and in shared-lib too.
story points are 140, 140, 136 for above order. That is why I am confused ;)

**Comment by mareknovotny** [comment]
All apps:
screenshot from 2016-06-01 10-01-09

Screenshots from collapsed archives in individual apps. All includes jee-example-web.war 
screenshot from 2016-06-01 10-01-33
screenshot from 2016-06-01 10-01-56
screenshot from 2016-06-01 10-02-15

**Comment by jsight** [comment]
That is as expected. The application_list page is wrong, though. There is another story for updating it.

**Comment by mareknovotny** [comment]
ok

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
Merging per discussion this morning...

**Pull request merged**
