### PR TITLE
WINDUP-545: Furnace is not started twice at Bootstrap anymore

### PR DESCRIPTION
**Pull request by mbriskar**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/637/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/6/
Test FAILed.

**Comment by mbriskar** [comment]
retest this please

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/8/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/639/
Test PASSed.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
This breaks "windup --help" completely.

**Comment by mbriskar** [comment]
jsightler > errors in console http://paste2.org/KPANjJ8f

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/654/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/24/
Test PASSed.

**Comment by mbriskar** [comment]
Fixed. 
windup --help output:  http://paste2.org/0U3f29yw
no errors in the logs in my case now (hopefully it is not nondeterministic)

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/657/
Test PASSed.

**Comment by jsight** [comment]
Looks good!

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/27/
Test PASSed.

**Pull request merged**
