### PR TITLE
WINDUP-452: NPE when executing windup from addon within Forge plugin in ...

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-452

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/326/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup.rules.apps:rules-java' /><a href='https://10.3.9.192/job/windup-pr-builder/326/org.jboss.windup.rules.apps$rules-java/testReport'>org.jboss.windup.rules.apps:rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/326/org.jboss.windup.rules.apps$rules-java/testReport/org.jboss.windup.rules.java/GatherIgnoredFilesTest/testJavaClassCondition/'><strong>org.jboss.windup.rules.java.GatherIgnoredFilesTest.testJavaClassCondition</strong></a></li></ul><h3><a name='org.jboss.windup.tests:tests' /><a href='https://10.3.9.192/job/windup-pr-builder/326/org.jboss.windup.tests$tests/testReport'>org.jboss.windup.tests:tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/326/org.jboss.windup.tests$tests/testReport/org.jboss.windup.tests.application/WindupRulesetMetadataTest/testRuleMetadata/'><strong>org.jboss.windup.tests.application.WindupRulesetMetadataTest.testRuleMetadata</strong></a></li></ul>
Test FAILed.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test PASSed.

**Comment by windupgithubbot1** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/328/
Test PASSed.

**Pull request merged**
