### PR TITLE
<version.furnace> 2.22.7.Final -> 2.22.10.Final

### PR DESCRIPTION
**Pull request by OndraZizka**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1386/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/758/

**Comment by jsight** [comment]
This needs to be updated in the bom/pom.xml as well.

**Comment by jsight** [comment]
Appears to have been obsoleted by https://github.com/windup/windup/pull/813/files

**Pull request closed without merging**
