### PR TITLE
Ui cleanup

### PR DESCRIPTION
**Pull request by bradsdavis**
Cleaned up the user interface.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
@windupgithubbot1 test this please

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/452/
Test PASSed.

**Comment by lincolnthree** [comment]
Please rebase this into a single commit. Thanks.

**Comment by lincolnthree** [comment]
Also please remove the static ip address report commit from this PR (unless it is dependent, at which point we'll need that to be merged before this can be merged.)

**Comment by jsight** [comment]
Merged https://github.com/windup/windup/commit/17d03d7adda19d735996676ce89da87f1e3fbe04

**Pull request closed without merging**
