### PR TITLE
WINDUP-1595 Javassist is out of date in Tattletale

### PR DESCRIPTION
**Pull request by OndraZizka**
Let's try this. I guess it needs building and running with that app.
I don't know which app that is though. Couldn't reproduce.

### CODE REVIEW

**Comment by mareknovotny** [comment]
Why 3.18.0-GA was chosen? 
I looked at release notes where it says full support of java 8 and I found only this comment at https://github.com/jboss-javassist/javassist/releases/tag/rel_3_19_0_ga

So we should upgrade to that or to https://github.com/jboss-javassist/javassist/releases/tag/rel_3_20_0_ga ?

**Comment by mareknovotny** [comment]
I have additional commit with managing dependencies even for other usage of javassist https://github.com/mareknovotny/windup/commit/8a78de9e67dca10d7c6283b5f27900896ffdda82

**Comment by OndraZizka** [comment]
I relied on the maven index which shown me 3.18 as the newest.

**Comment by OndraZizka** [comment]
Right, that's a good idea to have it centrally... maybe :) Assuming Javassist is fully backward compatible

**Comment by OndraZizka** [comment]
So let's use 3.21? Do you have a PR?

**Comment by OndraZizka** [comment]
I have moved the version declaration to <dependencyManagement> in root POM.

**Comment by mareknovotny** [comment]
there is still windup-frames hardcoded version, but I can fix it while merging

**Pull request merged**
