### PR TITLE
WINDUP-455 Make build compatible with Java 8

### PR DESCRIPTION
**Pull request by lincolnthree**

### CODE REVIEW

**Comment by gastaldi** [comment]
::+1::

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by gastaldi** [comment]
More info: https://issues.jboss.org/browse/FORGE-2019

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test PASSed.

**Comment by windupgithubbot1** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/334/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/335/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='org.jboss.windup.graph:windup-graph-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/335/org.jboss.windup.graph$windup-graph-tests/testReport'>org.jboss.windup.graph:windup-graph-tests</a>: <span class='status-failure'>3</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/335/org.jboss.windup.graph$windup-graph-tests/testReport/org.jboss.windup.graph.typedgraph.mapinprops/MapInPropertiesTest/testMapHandling/'><strong>org.jboss.windup.graph.typedgraph.mapinprops.MapInPropertiesTest.testMapHandling</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/335/org.jboss.windup.graph$windup-graph-tests/testReport/org.jboss.windup.graph.typedgraph.mapinprops/MapInPropertiesTest/testMapWithBlankPrefixHandling/'><strong>org.jboss.windup.graph.typedgraph.mapinprops.MapInPropertiesTest.testMapWithBlankPrefixHandling</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/335/org.jboss.windup.graph$windup-graph-tests/testReport/org.jboss.windup.graph.typedgraph.mapinprops/MapInPropertiesTest/testMapWithBlankPrefixHandling2/'><strong>org.jboss.windup.graph.typedgraph.mapinprops.MapInPropertiesTest.testMapWithBlankPrefixHandling2</strong></a></li></ul>
Test FAILed.

**Pull request merged**
