### PR TITLE
WINDUP-745 - removed 'Warnings: item(s)' and bullet from one line hin…

### PR DESCRIPTION
**Pull request by mareknovotny**
…t/classification message

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1028/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/400/
Test PASSed.

**Comment by jsight** [comment]
Great, thanks!

**Pull request merged**
