### PR TITLE
WINDUP-697: Titan graph fails to initialize when localhost cannot be resolved

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-697

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1041/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/413/
Test PASSed.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/417/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1046/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-ee-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/1046/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-ee-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/1046/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport/org.jboss.windup.rules.apps.javaee.tests/SpringDataSourceExtractionTest/testSpringBeans/'><strong>org.jboss.windup.rules.apps.javaee.tests.SpringDataSourceExtractionTest.testSpringBeans</strong></a></li></ul>
Test FAILed.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
@mareknovotny I have optimize imports turned on by default. The issue is that some people aren't setup with the same standard.

I am set to "java;javax;org;com;" and it would be nice if we all used the same standard.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1048/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/419/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1049/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/420/
Test PASSed.

**Pull request merged**
