### PR TITLE
Fixed package filtering during class file prescanning

### PR DESCRIPTION
**Pull request by jsight**

### CODE REVIEW

**Comment by OndraZizka** [comment]
I'm not sure if removing decomposition is a good idea, but better have it working than decomposed :)

**Comment by jsight** [comment]
@OndraZizka - What do you mean regarding removing decomposition? The only class that I removed was not used before at all (it was dead code).

**Comment by OndraZizka** [comment]
Right, I didn't notice...

**Comment by jsight** [comment]
@OndraZizka - Understood :) I only saw it because I was searching for any similar code that may have had similarly broken assumptions.

**Pull request merged**
