### PR TITLE
Add the URL for the output report to the console output

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
@windupgithubbot1 retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/444/
Test PASSed.

**Comment by jsight** [comment]
Merged https://github.com/windup/windup/commit/55e40516966322006e00353adfb197a14eddfdee

**Pull request closed without merging**
