### PR TITLE
JavaClass from/as fix

### PR DESCRIPTION
**Pull request by mbriskar**
It used to happen that JavaClass.compiledPattern didn't work in cases where JavaClass.from() was used.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-core-PR-dependents-check/487/
Test PASSed.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-pr-builder/1119/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins//job/windup-core-PR-dependents-check/488/<h2>Build result: FAILURE</span></h2>[...truncated 45290 lines...][JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/pom.xml to org.jboss.windup.quickstarts/windup-victims/2.4.0-SNAPSHOT/windup-victims-2.4.0-SNAPSHOT.pomchannel stoppedArchiving artifactsIRC notifier plugin: Sending notification to: #windupSetting status of 86c06d65c5d3886dae1c416d6b34439aa73d2865 to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com:9080/jenkins/job/windup-core-PR-dependents-check/488/ and message: Merged build finished.FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or that something is really wrong with github.java.io.FileNotFoundException: https://api.github.com/repos/windup/windup/statuses/86c06d65c5d3886dae1c416d6b34439aa73d2865	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)	at org.kohsuke.github.Requester.parse(Requester.java:383)	at org.kohsuke.github.Requester._to(Requester.java:185)	at org.kohsuke.github.Requester.to(Requester.java:160)	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:702)	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:714)	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:140)	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:122)	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:118)	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)	at hudson.model.Run.execute(Run.java:1802)	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)	at hudson.model.ResourceController.execute(ResourceController.java:89)	at hudson.model.Executor.run(Executor.java:240)
Test FAILed.

**Pull request merged**
