### PR TITLE
WINDUP-675: Display the Rule ID for a hint with a link to the rule report

### PR DESCRIPTION
**Pull request by jsight**
This also presents XML rules in a MUCH more readable way than before.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/274/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/905/
Test PASSed.

**Comment by mbriskar** [comment]
I think this PR contains two different issues, providing link and also providing xml for the rules in the Rule Providers. I think both are really useful, my only concern is if the user will understand that it is a link next to the provider. Even though it really looks nice and I would probably leave it that way, because we have a lot of information there already, so the minimum possible is good.
screenshot from 2015-07-03 12 25 04

**Comment by jsight** [comment]
Yes, the intent was for it to be subtle. I think the primary use is for debugging.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/911/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/280/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/282/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/913/
Test PASSed.

**Comment by lincolnthree** [comment]
Looks good. +1.

**Pull request merged**
