### PR TITLE
WINDUP-784: Fix sorting to be numeric instead of alphanumeric

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-784

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/460/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1092/
Test PASSed.

**Comment by mareknovotny** [comment]
it looks ok from me now

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/468/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1098/
Test PASSed.

**Pull request merged**
