### PR TITLE
WINDUP-439: Fix for new (related) unit test failure

### PR DESCRIPTION
**Pull request by jsight**

### CODE REVIEW

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by lincolnthree** [comment]
retest

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/321/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='org.jboss.windup.config:windup-config-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/321/org.jboss.windup.config$windup-config-tests/testReport'>org.jboss.windup.config:windup-config-tests</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/321/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.iteration/RuleIterationOverDefaultSingleVariableTest/testTypeSelection/'><strong>org.jboss.windup.config.iteration.RuleIterationOverDefaultSingleVariableTest.testTypeSelection</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/321/org.jboss.windup.config$windup-config-tests/testReport/org.jboss.windup.config.parameters/ParameterWiringTest/org_jboss_windup_config_parameters_ParameterWiringTest/'><strong>org.jboss.windup.config.parameters.ParameterWiringTest.org.jboss.windup.config.parameters.ParameterWiringTest</strong></a></li></ul><h3><a name='org.jboss.windup.reporting:windup-reporting-tests' /><a href='https://10.3.9.192/job/windup-pr-builder/321/org.jboss.windup.reporting$windup-reporting-tests/testReport'>org.jboss.windup.reporting:windup-reporting-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/321/org.jboss.windup.reporting$windup-reporting-tests/testReport/org.jboss.windup.reporting/ClassificationServiceTest/testHintEffort/'><strong>org.jboss.windup.reporting.ClassificationServiceTest.testHintEffort</strong></a></li></ul>
Test FAILed.

**Comment by jsight** [comment]
I'm not sure why this seemed to be necessary. Maybe it has been fixed elsewhere as I don't see the test failing in master now. Closing as outdated...

**Pull request closed without merging**
