### PR TITLE
WINDUP-504: XmlFile.inFile(***) is a ParameterizedPattern, not a Regex

### PR DESCRIPTION
**Pull request by mbriskar**
XSD schema PR fixed in/in-file, which I am using in this PR. Waiting for it to be merged

### CODE REVIEW

**Comment by jsight** [comment]
Which other PR does this depend on?

**Comment by lincolnthree** [comment]
I was about to ask that :)

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/482/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.rules.apps:rules-java-ee' /><a href='https://10.3.9.192/job/windup-pr-builder/482/org.jboss.windup.rules.apps$rules-java-ee/testReport'>org.jboss.windup.rules.apps:rules-java-ee</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/482/org.jboss.windup.rules.apps$rules-java-ee/testReport/org.jboss.windup.rules.apps.javaee.tests/XmlJonasConfigTest/testHintsAndClassificationOperation/'><strong>org.jboss.windup.rules.apps.javaee.tests.XmlJonasConfigTest.testHintsAndClassificationOperation</strong></a></li></ul>
Test FAILed.

**Comment by mbriskar** [comment]
Because of the test failing here, I fixed that in the XSD schema's PR. And put the information in the PR info :)

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/485/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup.rules.apps:rules-xml' /><a href='https://10.3.9.192/job/windup-pr-builder/485/org.jboss.windup.rules.apps$rules-xml/testReport'>org.jboss.windup.rules.apps:rules-xml</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://10.3.9.192/job/windup-pr-builder/485/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml/XMLTransformationXMLRulesTest/testXSLTTransformation/'><strong>org.jboss.windup.rules.xml.XMLTransformationXMLRulesTest.testXSLTTransformation</strong></a></li><li><a href='https://10.3.9.192/job/windup-pr-builder/485/org.jboss.windup.rules.apps$rules-xml/testReport/org.jboss.windup.rules.xml.handlers.unit/XmlFileHandlerTest/testXmlFileCondition/'><strong>org.jboss.windup.rules.xml.handlers.unit.XmlFileHandlerTest.testXmlFileCondition</strong></a></li></ul>
Test FAILed.

**Comment by lincolnthree** [comment]
Looks like some tests are failing?

**Comment by jsight** [comment]
@lincolnthree The tests are failing because it depends on the [xsd pr](https://github.com/windup/windup/pull/440).

**Comment by lincolnthree** [comment]
Ah, ok. Right.

**Comment by lincolnthree** [comment]
This looks good to me. Is it ready to review?

**Comment by lincolnthree** [comment]
Merged.

**Pull request closed without merging**
