### PR TITLE
WINDUP-864 - Fixed styling of boxes on expand

### PR DESCRIPTION
**Pull request by bradsdavis**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1270/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/644/

**Comment by bradsdavis** [comment]
@jsight Not sure why this would fail to build on a CSS change.  heh.

**Comment by jsight** [comment]
@bradsdavis The dependents check is failing due to an issue with master. :)

**Pull request merged**
