### PR TITLE
WINDUP-4136: upgrade commons-compress to v1.26.0

### PR DESCRIPTION
**Pull request by m-brophy**
[WINDUP-4136](https://issues.redhat.com/browse/WINDUP-4136)
[WINDUP-4137](https://issues.redhat.com/browse/WINDUP-4137)
[WINDUP-4138](https://issues.redhat.com/browse/WINDUP-4138)

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@carlosthe19916 - Can I ask you to review this PR from @m-brophy please?

**Comment by carlosthe19916** [comment]
I've verified all layers of Windups from windup-core to windup-openshift and all dependencies were updated correctly. Thanks @m-brophy

**Review by carlosthe19916 — APPROVED** [review]

**Comment by carlosthe19916** [comment]
@m-brophy @PhilipCattanach not sure if I can merge this PR so better to ask you. Feel free to merge this PR whenever you find it convenient

**Comment by PhilipCattanach** [comment]
Thanks @carlosthe19916 there is no reason why you shouldn't merge it. But I will. Thanks.

**Pull request merged**
