### PR TITLE
WINDUPRULE-214 dedup.

### PR DESCRIPTION
**Pull request by OndraZizka**
I didn't understand "This is overlapping with two other rules" but hopefully this is what was meant.

### CODE REVIEW

**Comment by mareknovotny** [comment]
I think there are additional classifications in the following classes, which are just irritating Marc too:

- org.jboss.windup.rules.apps.javaee.rules.websphere.ResolveWebSphereEjbExtensionXmlRuleProvider
- org.jboss.windup.rules.apps.javaee.rules.websphere.ResolveWebSphereEjbBindingXmlRuleProvider
- org.jboss.windup.rules.apps.javaee.rules.websphere.ResolveWebSphereWsBindingXmlRuleProvider
- org.jboss.windup.rules.apps.javaee.rules.websphere.ResolveWebSphereWsClientBindingXmlRuleProvider
- org.jboss.windup.rules.apps.javaee.rules.websphere.ResolveWebSphereWsExtBindingXmlRuleProvider

**Comment by jsight** [comment]
I think this doesn't fix the issue that Marc raised. He was specifically complaining about the "Vendor Specific EJB Specification Extension" classification as that one doesn't really add value on its own. Its only reason for being is to insure that a link exists in the reports from the issue to any transformed files.

My recommendation is to do one of the following:
 
- Change the GenerateJBossEjbDescriptorRuleProvider to set the classification to IssueDisplayMode.DETAIL_ONLY
- Remove the classification from GenerateJBossEjbDescriptorRuleProvider (I suspect that it is always redundant anyway) and insure that "setGenerateSourceReport" is called here.

My slight preference is towards the second one, but I don't really have a strong opinion either way.

**Comment by OndraZizka** [comment]
I admit I don't understand the requirement. What is it overlapping with? I hate the slideshow with screenshots. We can't continue like that. A screenshot is great to get oriented what the issue looks like but honestly, I can't read the text on it.

**Comment by jsight** [comment]
@OndraZizka - Is my description above not clear enough?

**Comment by OndraZizka** [comment]
Your description is ok, but I don't see a clear correlation between that and what Marc put in the slide. I am now following your comment.

**Comment by OndraZizka** [comment]
I looked at the other classes, but I am not sure whether these were really mentioned anywhere. It's not possible to seach through the slides.

**Comment by jsight** [comment]
I don't believe that the other ones were mentioned in the slides.

**Pull request merged**
