### PR TITLE
BOM update with proper style

### PR DESCRIPTION
**Pull request by OndraZizka**
Offering this polished shiny version of updated BOM, as requested.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by lincolnthree** [comment]
Very shiny. Thank you!

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test PASSed.

**Comment by windupgithubbot1** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/417/
Test PASSed.

**Pull request merged**
