### PR TITLE
WINDUP-1758 WINDUP-1768 CLI  option in list* commands

### PR DESCRIPTION
**Pull request by mrizzi**
The first commit has only the changes for `ListTagsCommand`.
If these changes are good, then i'll apply the same to `ListSourceTechnologiesCommand` and `ListTargetTechnologiesCommand`.

With these changes:

- executing CLI only with `--listTags` option still executes directly w/o any delay
- executing CLI with `--listTags` and `--userRulesDirectory /path/` options takes 5 seconds because it needs a `RuleProviderRegistryCache` from Furnace to get all the available tags from all the rules available

### CODE REVIEW

**Comment by jsight** [comment]
This seems like a good approach to me.

**Comment by windupgithubbot1** [comment]
Build triggered. sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build started sha1 is merged.

**Comment by mrizzi** [comment]
bcf7584 commit:

- refactored `List<Path> getUserProvidedPaths(List<String> arguments)` method in `AbstractListCommand` to check also the `~/.rhamt/rules` path for rules
- changes applied also to `ListSourceTechnologiesCommand` and `ListTargetTechnologiesCommand`

**Comment by windupgithubbot1** [comment]
Build triggered. sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build finished.

**Comment by windupgithubbot1** [comment]
Build started sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build finished.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
lgtm

**Pull request merged**
