### PR TITLE
Improve AbstractPathConfigurationOption's error messages.

### PR DESCRIPTION
**Pull request by OndraZizka**

### CODE REVIEW

**Comment by jsight** [comment]
I don't personally consider it an improvement to switch to the passive voice here.

**Comment by mareknovotny** [comment]
:) me neither, I think using MUST is signaling the importance more

**Comment by OndraZizka** [comment]
Don't you think the "ERROR: " in front of it is enough?
Also, I believe that in the RH corporate standards, yelling at users is discouraged. If this is printed, it is one of 4 lines printed. I don't think the user is going to miss the importance of the message which tells him why Windup didn't run.

**Comment by OndraZizka** [comment]
@bergerhoffer Andrea, WDYT - which is better?

$ windup.sh --input non-existent.file
ERROR: input must exist!

-- or -

$ windup.sh --input non-existent.file
ERROR: Option input must be an existing file: non-existent.file

**Comment by jsight** [comment]
@OndraZizka - We can take a poll on Monday. :) Feel free to bring it up then.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
(I suspect that this broke tests, btw)

**Pull request closed without merging**
