### PR TITLE
WINDUP-887: Refactor XmlFile

### PR DESCRIPTION
**Pull request by mbriskar**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1409/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/783/<h2>Build result: FAILURE</span></h2>[...truncated 65669 lines...][JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/classes/META-INF/resources/windup-victims-2.5.0-SNAPSHOT.dot to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT-forge-addon.jarchannel stoppedWeld SE container org.jboss.windup.rules.apps:windup-rules-java-archives shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java-project shut down by shutdown hookWeld SE container org.jboss.windup.ui:windup-ui shut down by shutdown hookWeld SE container org.jboss.windup.ast:windup-java-ast shut down by shutdown hookWeld SE container org.jboss.forge.addon:convert shut down by shutdown hookArchiving artifactsWeld SE container org.jboss.windup.config:windup-config-xml shut down by shutdown hookWeld SE container org.jboss.windup.config:windup-config-groovy shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-tattletale shut down by shutdown hookWeld SE container org.jboss.windup.exec:windup-exec shut down by shutdown hookWeld SE container org.jboss.windup:windup-tooling shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-base shut down by shutdown hookWeld SE container org.jboss.forge.addon:configuration shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-xml shut down by shutdown hookWeld SE container org.jboss.forge.addon:ui shut down by shutdown hookWeld SE container org.jboss.windup.config:windup-config shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java-ee shut down by shutdown hookWeld SE container org.jboss.windup.reporting:windup-reporting shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java shut down by shutdown hookIRC notifier plugin: Sending notification to: #windupSetting status of e72e8521a647343dbd4045b5655dde06a7f5f60c to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/783/ and message: 'Build finished. 5 tests run, 0 skipped, 0 failed.'

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1410/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/784/<h2>Build result: FAILURE</span></h2>[...truncated 65669 lines...][JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/classes/META-INF/resources/windup-victims-2.5.0-SNAPSHOT.dot to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT-forge-addon.jarchannel stoppedWeld SE container org.jboss.windup.ast:windup-java-ast shut down by shutdown hookWeld SE container org.jboss.forge.addon:configuration shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-base shut down by shutdown hookWeld SE container org.jboss.windup.ui:windup-ui shut down by shutdown hookArchiving artifactsWeld SE container org.jboss.windup.rules.apps:windup-rules-java-archives shut down by shutdown hookWeld SE container org.jboss.windup:windup-tooling shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-tattletale shut down by shutdown hookWeld SE container org.jboss.windup.config:windup-config-groovy shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java-project shut down by shutdown hookWeld SE container org.jboss.windup.exec:windup-exec shut down by shutdown hookWeld SE container org.jboss.windup.config:windup-config-xml shut down by shutdown hookWeld SE container org.jboss.forge.addon:convert shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-xml shut down by shutdown hookWeld SE container org.jboss.forge.addon:ui shut down by shutdown hookWeld SE container org.jboss.windup.config:windup-config shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java-ee shut down by shutdown hookWeld SE container org.jboss.windup.reporting:windup-reporting shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java shut down by shutdown hookIRC notifier plugin: Sending notification to: #windupSetting status of 4e510d3d7cb67d8f80d358a6014924cef3a98ca2 to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/784/ and message: 'Build finished. 5 tests run, 0 skipped, 0 failed.'

**Comment by mbriskar** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/787/<h2>Build result: FAILURE</span></h2>[...truncated 65669 lines...][JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/classes/META-INF/resources/windup-victims-2.5.0-SNAPSHOT.dot to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT-forge-addon.jarchannel stoppedWeld SE container org.jboss.windup.rules.apps:windup-rules-java-archives shut down by shutdown hookWeld SE container org.jboss.windup.config:windup-config-groovy shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java-project shut down by shutdown hookWeld SE container org.jboss.windup.ui:windup-ui shut down by shutdown hookWeld SE container org.jboss.forge.addon:convert shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-tattletale shut down by shutdown hookWeld SE container org.jboss.windup.ast:windup-java-ast shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-base shut down by shutdown hookWeld SE container org.jboss.windup:windup-tooling shut down by shutdown hookArchiving artifactsWeld SE container org.jboss.forge.addon:configuration shut down by shutdown hookWeld SE container org.jboss.windup.config:windup-config-xml shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-xml shut down by shutdown hookWeld SE container org.jboss.windup.exec:windup-exec shut down by shutdown hookWeld SE container org.jboss.forge.addon:ui shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java-ee shut down by shutdown hookWeld SE container org.jboss.windup.config:windup-config shut down by shutdown hookWeld SE container org.jboss.windup.reporting:windup-reporting shut down by shutdown hookWeld SE container org.jboss.windup.rules.apps:windup-rules-java shut down by shutdown hookIRC notifier plugin: Sending notification to: #windupSetting status of 4e510d3d7cb67d8f80d358a6014924cef3a98ca2 to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/787/ and message: 'Build finished. 5 tests run, 0 skipped, 0 failed.'

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1414/<h2>Build result: ABORTED</span></h2>[...truncated 154302 lines...]Feb 02, 2016 9:16:36 AM org.jboss.forge.furnace.impl.addons.AddonLoader loadAddonWARNING: Addon [org.jboss.windup.config:windup-config-xml,2.5.0-SNAPSHOT +NEW] has [2] missing dependencies: [[MISSING: org.jboss.windup.config:windup-config,2.5.0-SNAPSHOT: [IMPORTED/EXPORTED] [REQUIRED]], [MISSING: org.jboss.forge.furnace.container:cdi,2.22.10.Final: [IMPORTED] [REQUIRED]]] and will be not be loaded until all required dependencies are available.Feb 02, 2016 9:16:36 AM org.jboss.forge.furnace.impl.addons.AddonLoader loadAddonWARNING: Addon [org.jboss.windup.rules.apps:windup-rules-base,2.5.0-SNAPSHOT +NEW] has [3] missing dependencies: [[MISSING: org.jboss.windup.config:windup-config,2.5.0-SNAPSHOT: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.forge.furnace.container:cdi,2.22.10.Final: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.config:windup-config-xml,2.5.0-SNAPSHOT: [IMPORTED] [REQUIRED]]] and will be not be loaded until all required dependencies are available.Feb 02, 2016 9:16:36 AM org.jboss.forge.furnace.impl.addons.AddonLoader loadAddonWARNING: Addon [org.jboss.windup.rules.apps:windup-rules-xml,2.5.0-SNAPSHOT +NEW] has [5] missing dependencies: [[MISSING: org.jboss.windup.rules.apps:windup-rules-base,2.5.0-SNAPSHOT: [IMPORTED/EXPORTED] [REQUIRED]], [MISSING: org.jboss.windup.reporting:windup-reporting,2.5.0-SNAPSHOT: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.config:windup-config,2.5.0-SNAPSHOT: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.forge.furnace.container:cdi,2.22.10.Final: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.config:windup-config-xml,2.5.0-SNAPSHOT: [IMPORTED] [REQUIRED]]] and will be not be loaded until all required dependencies are available.Feb 02, 2016 9:16:36 AM org.jboss.forge.furnace.impl.addons.AddonLoader loadAddonWARNING: Addon [org.jboss.windup.ast:windup-java-ast,2.5.0-SNAPSHOT +NEW] has [1] missing dependencies: [[MISSING: org.jboss.forge.furnace.container:cdi,2.22.10.Final: [IMPORTED] [REQUIRED]]] and will be not be loaded until all required dependencies are available.Feb 02, 2016 9:16:36 AM org.jboss.forge.furnace.impl.addons.AddonLoader loadAddonWARNING: Addon [org.jboss.forge.addon:configuration,2.20.2.Final +NEW] has [1] missing dependencies: [[MISSING: org.jboss.forge.furnace.container:cdi,2.22.10.Final: [IMPORTED] [REQUIRED]]] and will be not be loaded until all required dependencies are available.Feb 02, 2016 9:16:36 AM org.jboss.forge.furnace.impl.addons.AddonLoader loadAddonWARNING: Addon [org.jboss.windup.rules.apps:windup-rules-java-archives,2.5.0-SNAPSHOT +NEW] has [5] missing dependencies: [[MISSING: org.jboss.windup.config:windup-config-groovy,2.5.0-SNAPSHOT: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.graph:windup-graph,2.5.0-SNAPSHOT: [IMPORTED/EXPORTED] [REQUIRED]], [MISSING: org.jboss.windup.reporting:windup-reporting,2.5.0-SNAPSHOT: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.config:windup-config,2.5.0-SNAPSHOT: [IMPORTED/EXPORTED] [REQUIRED]], [MISSING: org.jboss.forge.furnace.container:cdi,2.22.10.Final: [IMPORTED] [REQUIRED]]] and will be not be loaded until all required dependencies are available.Feb 02, 2016 9:16:36 AM org.jboss.forge.furnace.impl.addons.AddonLoader loadAddonWARNING: Addon [_DEFAULT_,7413d46d-a683-4fcb-a6c5-4eb4ab21822d +NEW] has [9] missing dependencies: [[MISSING: org.jboss.windup.graph:windup-graph,: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.reporting:windup-reporting,: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.exec:windup-exec,: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.rules.apps:windup-rules-java,: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.rules.apps:windup-rules-java-ee,: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.rules.apps:windup-rules-tattletale,: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.tests:test-util,: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.windup.config:windup-config-groovy,: [IMPORTED] [REQUIRED]], [MISSING: org.jboss.forge.furnace.container:cdi,: [IMPORTED] [REQUIRED]]] and will be not be loaded until all required dependencies are available.Feb 02, 2016 9:16:36 AM org.jboss.forge.furnace.impl.addons.AddonLoader loadAddonWARNING: Addon [org.jboss.forge.addon:maven,2.20.2.Final +NEW] has [1] missing dependencies: [[MISSING: org.jboss.forge.addon:configuration,2.20.2.Final: [IMPORTED/EXPORTED] [REQUIRED]]] and will be not be loaded until all required dependencies are available.Furnace test harness is undeploying [_DEFAULT_,7413d46d-a683-4fcb-a6c5-4eb4ab21822d] ... Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 183.959 sec - in org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTestBuild was abortedAborted by Marek Novotnychannel stoppedArchiving artifactsIRC notifier plugin: Sending notification to: #windupSetting status of 4e510d3d7cb67d8f80d358a6014924cef3a98ca2 to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1414/ and message: 'Build finished. 403 tests run, 4 skipped, 0 failed.'

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1418/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='windup-pr-builder/org.jboss.windup.rexster:windup-rexster-tests' /><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1418/org.jboss.windup.rexster$windup-rexster-tests/testReport'>windup-pr-builder/org.jboss.windup.rexster:windup-rexster-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1418/org.jboss.windup.rexster$windup-rexster-tests/testReport/org.jboss.windup.graph.rexster.test/RexsterTest/testRexsterProperStart/'><strong>org.jboss.windup.graph.rexster.test.RexsterTest.testRexsterProperStart</strong></a></li></ul>

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/794/

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/803/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1425/

**Pull request merged**
