### PR TITLE
WINDUP-542: Fix severe regression in AST performance

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-542

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/615/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/616/<h2>Failed Tests: <span class='status-failure'>7</span></h2><h3><a name='org.jboss.windup.ast:windup-java-ast-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.ast$windup-java-ast-tests/testReport'>org.jboss.windup.ast:windup-java-ast-tests</a>: <span class='status-failure'>5</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaASTProcessorTest/testMyAClass/'><strong>org.jboss.windup.ast.java.test.JavaASTProcessorTest.testMyAClass</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaASTProcessorTest/testMyBClass/'><strong>org.jboss.windup.ast.java.test.JavaASTProcessorTest.testMyBClass</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaASTProcessorTest/testJavaLangReferences/'><strong>org.jboss.windup.ast.java.test.JavaASTProcessorTest.testJavaLangReferences</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaASTProcessorTest/testHelloWorld/'><strong>org.jboss.windup.ast.java.test.JavaASTProcessorTest.testHelloWorld</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaAnnotationScanningTest/testComplexAnnotatedClass/'><strong>org.jboss.windup.ast.java.test.JavaAnnotationScanningTest.testComplexAnnotatedClass</strong></a></li></ul><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.apps.java.scan.ast/VariableResolvingASTIntegrationTest/testJavaSourceScanning/'><strong>org.jboss.windup.rules.apps.java.scan.ast.VariableResolvingASTIntegrationTest.testJavaSourceScanning</strong></a></li></ul><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/616/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li></ul>
Test FAILed.

**Comment by jsight** [comment]
I'm pulling this back for some tweaks... It's a lot faster, but there are a few issues left here.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/617/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/618/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/619/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/620/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/620/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/620/org.jboss.windup.rules.apps$windup-rules-java-tests/testReport/org.jboss.windup.rules.apps.java.scan.ast/VariableResolvingASTIntegrationTest/testJavaSourceScanning/'><strong>org.jboss.windup.rules.apps.java.scan.ast.VariableResolvingASTIntegrationTest.testJavaSourceScanning</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/621/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/623/
Test PASSed.

**Comment by jsight** [comment]
I think that I will call this ready for review. I wanted to use the batch method to process multiple files through JDT at a time, but this caused all sorts of problems (memory problems, skipping files, more memory problems that manifested as skipping files, etc).

As it is, this does at least improve performance some.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/624/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/625/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/627/
Test PASSed.

**Pull request merged**
