### PR TITLE
T617 Upgrade forge and furnace

### PR DESCRIPTION
**Pull request by OndraZizka**
Comes with https://github.com/windup/windup-web/pull/272
which fails on something in TsModelGen.
Comes with https://github.com/windup/windup-quickstarts/pull/83

### CODE REVIEW

**Comment by OndraZizka** [comment]
Comes with https://github.com/windup/windup-web/pull/272
which fails on something in TsModelGen.

**Comment by jsight** [comment]
retest

**Comment by OndraZizka** [comment]
```
[ERROR] /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/src/test/java/org/jboss/windup/qs/victims/test/VictimsRulesetTest.java:[15,42] cannot find symbol
  symbol:   class ForgeArchive
  location: package org.jboss.forge.arquillian.archive
```

**Comment by mareknovotny** [comment]
there is also https://github.com/windup/windup-maven-plugin/pull/11

**Comment by jsight** [comment]
retest

**Pull request merged**
