### PR TITLE
WINDUP-891: Migration Issues Report: Mandatory type issues should be first in the table

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-891

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1398/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/770/<h2>Build result: FAILURE</span></h2>[...truncated 64325 lines...][ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/maven-plugin-usage/pom.xml to org.jboss.windup.quickstarts/maven-plugin-usage/2.5.0-SNAPSHOT/maven-plugin-usage-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/pom.xml to org.jboss.windup.jenkins/windup-core-dependents-aggregate-pom/2.3.0-SNAPSHOT/windup-core-dependents-aggregate-pom-2.3.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/rules-java/target/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet-rules-java/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/pom.xml to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-rulesets/target/windup-rulesets-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.rules/windup-rulesets/2.5.0-SNAPSHOT/windup-rulesets-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/proprietary-javaee-servlet/pom.xml to org.jboss.windup.quickstarts/windup-proprietary-javaee-servlet/2.5.0-SNAPSHOT/windup-proprietary-javaee-servlet-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/pom.xml to org.jboss.windup.quickstarts/windup-quickstarts-root/2.5.0-SNAPSHOT/windup-quickstarts-root-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/rules-java/target/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-ejb-beanutils-async-rules-java/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-rules-java-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/ejb-beanutils-async/pom.xml to org.jboss.windup.quickstarts/windup-ejb-beanutils-async/2.5.0-SNAPSHOT/windup-ejb-beanutils-async-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/pom.xml to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/classes/META-INF/resources/windup-victims-2.5.0-SNAPSHOT.dot to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/target/windup-victims-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.quickstarts/windup-victims/2.5.0-SNAPSHOT/windup-victims-2.5.0-SNAPSHOT-forge-addon.jarchannel stoppedArchiving artifactsIRC notifier plugin: Sending notification to: #windupSetting status of 834c1065ad744d0234b072b34ff2efe535fb1266 to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/770/ and message: 'Build finished. 5 tests run, 0 skipped, 0 failed.'

**Comment by mareknovotny** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1401/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='windup-pr-builder/org.jboss.windup.rexster:windup-rexster-tests' /><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1401/org.jboss.windup.rexster$windup-rexster-tests/testReport'>windup-pr-builder/org.jboss.windup.rexster:windup-rexster-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1401/org.jboss.windup.rexster$windup-rexster-tests/testReport/org.jboss.windup.graph.rexster.test/RexsterTest/testRexsterProperStart/'><strong>org.jboss.windup.graph.rexster.test.RexsterTest.testRexsterProperStart</strong></a></li></ul>

**Comment by mareknovotny** [comment]
:) I was confused for a few minutes by commit text which seems is the same as in https://github.com/windup/windup/pull/819

**Comment by mareknovotny** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/775/

**Comment by jsight** [comment]
@mareknovotny - Yeah, apparently I copied the test from the wrong JIRA. Ooops (rebased and fixed now).

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1402/<h2>Build result: FAILURE</span></h2>[...truncated 154483 lines...][JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/test-util/target/test-util-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.tests/test-util/2.5.0-SNAPSHOT/test-util-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/test-util/target/test-util-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.tests/test-util/2.5.0-SNAPSHOT/test-util-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/config/api/pom.xml to org.jboss.windup.config/windup-config-api/2.5.0-SNAPSHOT/windup-config-api-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/config/api/target/windup-config-api-2.5.0-SNAPSHOT.jar to org.jboss.windup.config/windup-config-api/2.5.0-SNAPSHOT/windup-config-api-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/config/api/target/windup-config-api-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.config/windup-config-api/2.5.0-SNAPSHOT/windup-config-api-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/rules-xml/pom.xml to org.jboss.windup.rules.apps/windup-rules-xml-parent/2.5.0-SNAPSHOT/windup-rules-xml-parent-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/rexster/addon/pom.xml to org.jboss.windup.rexster/windup-rexster/2.5.0-SNAPSHOT/windup-rexster-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/rexster/addon/target/windup-rexster-2.5.0-SNAPSHOT.jar to org.jboss.windup.rexster/windup-rexster/2.5.0-SNAPSHOT/windup-rexster-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/rexster/addon/target/classes/META-INF/resources/windup-rexster-2.5.0-SNAPSHOT.dot to org.jboss.windup.rexster/windup-rexster/2.5.0-SNAPSHOT/windup-rexster-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/rexster/addon/target/windup-rexster-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.rexster/windup-rexster/2.5.0-SNAPSHOT/windup-rexster-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/rexster/addon/target/windup-rexster-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.rexster/windup-rexster/2.5.0-SNAPSHOT/windup-rexster-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/forks/procyon/Procyon.Core/pom.xml to org.jboss.windup.decompiler.procyon/procyon-core/2.5.0-SNAPSHOT/procyon-core-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/forks/procyon/Procyon.Core/target/procyon-core-2.5.0-SNAPSHOT.jar to org.jboss.windup.decompiler.procyon/procyon-core/2.5.0-SNAPSHOT/procyon-core-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/forks/procyon/Procyon.Core/target/procyon-core-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.decompiler.procyon/procyon-core/2.5.0-SNAPSHOT/procyon-core-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/reporting/addon/pom.xml to org.jboss.windup.reporting/windup-reporting/2.5.0-SNAPSHOT/windup-reporting-2.5.0-SNAPSHOT.pom[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/reporting/addon/target/windup-reporting-2.5.0-SNAPSHOT.jar to org.jboss.windup.reporting/windup-reporting/2.5.0-SNAPSHOT/windup-reporting-2.5.0-SNAPSHOT.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/reporting/addon/target/classes/META-INF/resources/windup-reporting-2.5.0-SNAPSHOT.dot to org.jboss.windup.reporting/windup-reporting/2.5.0-SNAPSHOT/windup-reporting-2.5.0-SNAPSHOT.dot[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/reporting/addon/target/windup-reporting-2.5.0-SNAPSHOT-sources.jar to org.jboss.windup.reporting/windup-reporting/2.5.0-SNAPSHOT/windup-reporting-2.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/reporting/addon/target/windup-reporting-2.5.0-SNAPSHOT-forge-addon.jar to org.jboss.windup.reporting/windup-reporting/2.5.0-SNAPSHOT/windup-reporting-2.5.0-SNAPSHOT-forge-addon.jar[JENKINS] Archiving /var/lib/jenkins/workspace/windup-pr-builder/rules-java-archives/pom.xml to org.jboss.windup.rules.apps/windup-rules-java-archives-parent/2.5.0-SNAPSHOT/windup-rules-java-archives-parent-2.5.0-SNAPSHOT.pomchannel stoppedArchiving artifactsIRC notifier plugin: Sending notification to: #windupSetting status of 834c1065ad744d0234b072b34ff2efe535fb1266 to FAILURE with url http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1402/ and message: 'Build finished. 507 tests run, 5 skipped, 0 failed.'

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/776/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1403/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/777/

**Comment by mareknovotny** [comment]
+1

**Pull request merged**
