### PR TITLE
T146 Show how many points in the app came from shared-libs within app list row

### PR DESCRIPTION
**Pull request by OndraZizka**

### CODE REVIEW

**Comment by jsight** [comment]
Hi @OndraZizka - Can you update the status of this? Is there anything that I can help with here?

**Comment by OndraZizka** [comment]
Updating now.

**Comment by OndraZizka** [comment]
After rebasing, the numbers seem to be wrong.

**Comment by OndraZizka** [comment]
Fixing

**Comment by OndraZizka** [comment]
See WINDUP-1088

**Comment by OndraZizka** [comment]
I suspect there's one more bug, the traversal somehow counting the root project without checking it or something like that.

**Comment by OndraZizka** [comment]
This is "ready for review", but I am leaving the debugging log output in, because I assume whoever takes it from here might need that.

**Comment by jsight** [comment]
Merged: https://github.com/windup/windup/commit/ad7b6b48bc901b3bfa6a6e42d13543558b3db5c5

**Pull request closed without merging**
