### PR TITLE
WINDUP-1008 Improve the layout of Application List

### PR DESCRIPTION
**Pull request by OndraZizka**
See jira for screenshots.

### CODE REVIEW

**Comment by OndraZizka** [comment]
retest

**Comment by OndraZizka** [comment]
This will probably need an update of tests.

**Comment by mareknovotny** [comment]
I think al such layout changes requires confirmation from the our team not only committers ;)

**Comment by OndraZizka** [comment]
retest

**Comment by jsight** [comment]
+1 - This is actually a major change to the layout that will need more extensive review.

**Comment by OndraZizka** [comment]
In my opinion, there's no doubt this is better. But who knows, maybe someone will like the table layout for non tabular data more, until someone from UX tells it's really not nice ;-)

**Comment by jsight** [comment]
If nothing else, I really dislike the little x's all over the numbers.

**Comment by OndraZizka** [comment]
That indicates that it's not story points. Imo just numbers is pretty confusing and we heard that many times.

**Comment by d-s** [comment]
Agreed that we shouldn't just cram this PR in without review/discussion,
but I do think it looks really nice -- and more in sync with the
application details report.

(I don't love the Xs myself, but the charts in the application details
report already present incident counts the same way, and I can't really
think of a better way to communicate incident counts vs. story points...)

**Comment by mareknovotny** [comment]
I think times symbol is good to imagine on first view what it is, and the columns really looks more like overview which is good. 
I haven't commented on order of columns as that is only disputable what should be in first, second etc. and if we want to provide sorting. I think this will be the major point for discussion with Robb and Tobias.

**Comment by OndraZizka** [comment]
Squashed

**Comment by OndraZizka** [comment]
Ok so I will update the tests and merge this, as agreed on Monday's meeting.

**Comment by OndraZizka** [comment]
Also, it got broken over time, need to fix the CSS.

**Comment by jsight** [comment]
retest

**Comment by OndraZizka** [comment]
retest

**Pull request merged**
