### PR TITLE
Fix charts to use category id and not display 0 items

### PR DESCRIPTION
**Pull request by jsight**
Just until something like https://github.com/windup/windup/pull/1096 can be approved.

### CODE REVIEW

**Comment by mareknovotny** [comment]
I don't understand if you took https://github.com/windup/windup/pull/1096 and changed a little it or you still are waiting on merging https://github.com/windup/windup/pull/1096. 
I see changes in master branch, but not all things like css styles.

**Comment by jsight** [comment]
Extensive changes like this to this page require a review from Tobias and Marc. So I did a much smaller version.

We can present this to them when we have time, though.

**Comment by mareknovotny** [comment]
:o there were just syncing to have the similar what is in dynamic report index

**Comment by jsight** [comment]
I know, but those are completely new and are being reviewed weekly (or at least they should be). This could come as an unexpected surprise.

**Pull request merged**
