### PR TITLE
WINDUP-620: Return classreferences for wildcard imports

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-620

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/807/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/173/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java' /><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/173/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport'>org.jboss.windup.quickstarts:windup-ejb-beanutils-async-rules-java</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-core-PR-dependents-check/173/org.jboss.windup.quickstarts$windup-ejb-beanutils-async-rules-java/testReport/org.jboss.windup.qs.rules/EjbBeanUtilsAsyncUsageRuleProviderTest/testRules/'><strong>org.jboss.windup.qs.rules.EjbBeanUtilsAsyncUsageRuleProviderTest.testRules</strong></a></li></ul>
Test FAILed.

**Comment by mbriskar** [comment]
1) I am not sure what the final javaclass condition look like. references="java.net.*"?
2) What about registering it only if we didn't find any resolvedname? Or is there any other usage except to just show unused imports (because no class is present)?

**Comment by jsight** [comment]
@mbriskar - Yes, I think it would look like reference="java.net.*".

I considered registering it only in that case. My concern is that a rule may want to flag a wildcard import, even though we know of some of the specific classes inside of that import. Do you think that is possible?

**Comment by mbriskar** [comment]
I don't see much point in searching for wildcard's only. It may be then a rule searching for ".*" - e.g all wildcard imports, but why to search for specific wildcards?

**Pull request merged**
