### PR TITLE
WINDUP-755: In Migration Issues Report, roll up all static IP issues into 1

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-755

This should fix https://issues.jboss.org/browse/WINDUP-673 as well.

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/1039/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/411/
Test PASSed.

**Comment by mareknovotny** [comment]
+1
it looks much better than listing all different IP addresses.

**Comment by jsight** [comment]
Thanks @mareknovotny

**Pull request merged**
