### PR TITLE
WINDUP-575 - Hibernate styling & cleanup of empty report elements

### PR DESCRIPTION
**Pull request by bradsdavis**
Fixed hibernate styling for tables; this was missed in the previous WINDUP-575 pull request.

### CODE REVIEW

**Comment by lincolnthree** [comment]
Hey Brad, 

Could you rebase this to include the name of the JIRA in the commit? 

rebase -i HEAD~1 

Then change "pick" to 'r' for this commit. (should be the first word in the line of the editor)

Then save/quit

Then rename the commit to:

WINDUP-575: Fixed tables in Hibernate report.

Then save/quit


Thanks!
~Lincoln

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/710/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/82/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/83/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/711/
Test PASSed.

**Comment by lincolnthree** [comment]
Merged.

**Pull request closed without merging**
