### PR TITLE
T550 Skip HTML reports rendering

### PR DESCRIPTION
**Pull request by OndraZizka**
Refactor PhaseHandler, spin off RulePhaseFinder, split interface and impl where needed to get it through furnace

### CODE REVIEW

**Comment by OndraZizka** [comment]
Fixed tests

**Comment by OndraZizka** [comment]
For PR-dependents:  https://github.com/windup/windup-quickstarts/pull/82

**Comment by OndraZizka** [comment]
retest

**Comment by mareknovotny** [comment]
As you rely on change in Quickstarts the job windup-core-PR-dependents-check fails until you merge this change. But as now this change and related quickstarts tests/build ills jenkins CI temp disk, I would recommend not to trigger the CI with this until we limit the filling.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by OndraZizka** [comment]
@mareknovotny  Why the bug tag?

**Comment by jsight** [comment]
This seems like a reasonable simplification. +1

**Pull request merged**
