### PR TITLE
WINDUP-648 fixed always plural items in java application reports template

### PR DESCRIPTION
**Pull request by mareknovotny**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by mbriskar** [comment]
do you have an example of only 1 warning just to check it works on my machine?

**Comment by mareknovotny** [comment]
yes, look at jira http://issues.jboss.org/browse/WINDUP-648, there is attached example report for weblogic rules https://issues.jboss.org/secure/attachment/12390464/Project___home_mnovotny_projects_git_windup_rulesets_rules_reviewed_jboss_eap_weblogic_tests_data.html

**Comment by lincolnthree** [comment]
Is this ready for review?

**Comment by lincolnthree** [comment]
@mareknovotny you should now have access to set Labels. sorry about that.

**Comment by mareknovotny** [comment]
@lincolnthree  thanks for the given permission.

**Pull request merged**
