### PR TITLE
WINDUP-633 - Provide a method of registering hints/classifications fo…

### PR DESCRIPTION
**Pull request by lincolnthree**
https://issues.jboss.org/browse/WINDUP-633

### CODE REVIEW

**Comment by jsight** [comment]
If the tests pass,t his looks good to me.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/828/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/196/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/830/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/198/
Test PASSed.

**Comment by mbriskar** [comment]
I like it too :)

**Comment by lincolnthree** [comment]
Awesome :)

**Pull request merged**
