### PR TITLE
Full Annotation Parsing

### PR DESCRIPTION
**Pull request by jsight**
This cleans up some hackiness around annotations (essentially allowing us to pull out any annotation value).

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/585/<h2>Failed Tests: <span class='status-failure'>11</span></h2><h3><a name='org.jboss.windup.rules.apps:windup-rules-java-ee-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport'>org.jboss.windup.rules.apps:windup-rules-java-ee-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.rules.apps$windup-rules-java-ee-tests/testReport/org.jboss.windup.rules.apps.javaee.tests/DiscoverEjbConfigurationTest/testEJBMetadataExtraction/'><strong>org.jboss.windup.rules.apps.javaee.tests.DiscoverEjbConfigurationTest.testEJBMetadataExtraction</strong></a></li></ul><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>10</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureHibernateTest/testRunWindupHibernate/'><strong>org.jboss.windup.tests.application.WindupArchitectureHibernateTest.testRunWindupHibernate</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureScanPackagesTest/testRunWindupScanPackages/'><strong>org.jboss.windup.tests.application.WindupArchitectureScanPackagesTest.testRunWindupScanPackages</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryMode2Test/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryMode2Test.testRunWindupTiny</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSmallBinaryModeTest/testRunWindupTiny/'><strong>org.jboss.windup.tests.application.WindupArchitectureSmallBinaryModeTest.testRunWindupTiny</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSoa5GatewaysRoutersTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSoa5GatewaysRoutersTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/585/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSpringSmallTest/testRunWindupSmallSpringApp/'><strong>org.jboss.windup.tests.application.WindupArchitectureSpringSmallTest.testRunWindupSmallSpringApp</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/586/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/586/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>3</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/586/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureMediumBinaryModeTest/testRunWindupMedium/'><strong>org.jboss.windup.tests.application.WindupArchitectureMediumBinaryModeTest.testRunWindupMedium</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/586/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/586/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/588/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/588/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>2</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/588/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/588/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/589/<h2>Failed Tests: <span class='status-failure'>9</span></h2><h3><a name='org.jboss.windup.ast:windup-java-ast-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.ast$windup-java-ast-tests/testReport'>org.jboss.windup.ast:windup-java-ast-tests</a>: <span class='status-failure'>7</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java/JavaASTProcessorTest/testSimpleMain/'><strong>org.jboss.windup.ast.java.JavaASTProcessorTest.testSimpleMain</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java/JavaASTProcessorTest/testMyAClass/'><strong>org.jboss.windup.ast.java.JavaASTProcessorTest.testMyAClass</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java/JavaASTProcessorTest/testMyBClass/'><strong>org.jboss.windup.ast.java.JavaASTProcessorTest.testMyBClass</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaASTProcessorTest/testSimpleMain/'><strong>org.jboss.windup.ast.java.test.JavaASTProcessorTest.testSimpleMain</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaASTProcessorTest/testMyAClass/'><strong>org.jboss.windup.ast.java.test.JavaASTProcessorTest.testMyAClass</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaASTProcessorTest/testMyBClass/'><strong>org.jboss.windup.ast.java.test.JavaASTProcessorTest.testMyBClass</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.ast$windup-java-ast-tests/testReport/org.jboss.windup.ast.java.test/JavaASTProcessorTest/testJavaLangReferences/'><strong>org.jboss.windup.ast.java.test.JavaASTProcessorTest.testJavaLangReferences</strong></a></li></ul><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>2</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSeamBookingSourceTest/testRunWindupSeamBookingSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSeamBookingSourceTest.testRunWindupSeamBookingSourceMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/589/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/590/
Test PASSed.

**Comment by lincolnthree** [comment]
Looks good, but I think that the name of the commit should probably be updated.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/601/
Test PASSed.

**Pull request merged**
