### PR TITLE
WINDUP-1049  Running with JDK 7 fails due nexus-index built and deplo…

### PR DESCRIPTION
**Pull request by OndraZizka**
This upgrades nexus-indexer-data 6.1.

I have released nexus-indexer 6.1. Waiting for it to appear in the repositories.
http://repository.jboss.org/nexus/content/groups/public/org/jboss/windup/maven/nexus-indexer-data/
http://search.maven.org/#search|gav|1|g%3A%22org.jboss.windup.maven%22%20AND%20a%3A%22nexus-indexer-data%22

### CODE REVIEW

**Comment by OndraZizka** [comment]
Seems it's already in jboss repo.
https://repository.jboss.org/nexus/#nexus-search;quick~nexus-indexer-data

**Comment by mareknovotny** [comment]
retest

**Comment by mareknovotny** [comment]
marked as Bug until tests passed ;)

**Comment by mareknovotny** [comment]
Test failures

**Comment by OndraZizka** [comment]
This depends on the nexus-indexer release. It's not a bug, the tests will fail until the release gets to maven central.

**Comment by mareknovotny** [comment]
I thought you were deployed it and it should synced up almost immediately, and I can see it in Central already here http://search.maven.org/#artifactdetails|org.jboss.windup.maven|nexus-indexer-data|6.1|jar

**Comment by mareknovotny** [comment]
retest

**Comment by jsight** [comment]
retest

**Pull request merged**
