### PR TITLE
WINDUP-1957: make error display bar reusable

### PR DESCRIPTION
**Pull request by m-brophy**
This should fix the problem Marco found yesterday

### CODE REVIEW

**Comment by jsight** [comment]
lgtm

**Comment by jsight** [comment]
@mrizzi - Hmm, I'm seeing the same glitchiness. Not sure what is going on there?

**Comment by jsight** [comment]
Maybe this is related? https://stackoverflow.com/questions/34658730/bootstrap-collapse-expanding-too-far-when-first-clicked

**Comment by mrizzi** [comment]
> Maybe this is related? https://stackoverflow.com/questions/34658730/bootstrap-collapse-expanding-too-far-when-first-clicked

It seems very similar.
@m-brophy can you try it on this PR please?

**Comment by m-brophy** [comment]
I do get that, yes, I thought it was just an animation for the collapse/reopen actions. I'll try the advice in that SO accepted answer.

**Comment by m-brophy** [comment]
Ready to review/retest again

**Comment by jsight** [comment]
I am getting another strange behavior. The error box seems to appear on the first search, even if I enter a valid value.

**Comment by m-brophy** [comment]
Ready for a retest again

**Pull request merged**
