### PR TITLE
WINDUP-1009 Replace commons-lang 2.x with 3.x

### PR DESCRIPTION
**Pull request by OndraZizka**
Also related to WINDUP-1007 Review the flat dependencies of windup-distribution

### CODE REVIEW

**Comment by jsight** [comment]
@windupgithubbot1 retest

**Comment by OndraZizka** [comment]
retest

**Comment by mareknovotny** [comment]
@windupgithubbot1 retest

**Comment by mareknovotny** [comment]
It seems that jenkins is stalled or so, I ran tests locally and all passed.

**Comment by jsight** [comment]
After this change, commons-logging 3 is now deployed in three new places within windup:
addons/org-jboss-windup-rules-apps-windup-rules-java-ee-2-5-0-SNAPSHOT/commons-lang3-3.4.jar
addons/org-jboss-windup-graph-windup-graph-2-5-0-SNAPSHOT/commons-lang3-3.4.jar
addons/org-jboss-windup-rules-apps-windup-rules-java-2-5-0-SNAPSHOT/commons-lang3-3.4.jar

That seems strange to me and makes think that the dependencies aren't fully thought out here.

**Comment by OndraZizka** [comment]
retest

**Comment by OndraZizka** [comment]
@jsight   That's what I was talkinb about at the meeting - the dependencies are wrong in master, not in this PR. The commons-lang3 is used at those places because some other dependency has it. That's wrong, IMO. And we do that a lot BTW.

**Comment by jsight** [comment]
Including it in 3 extra addons is actually worse, though.

**Comment by OndraZizka** [comment]
How is it worse? If we removed the deps from the addons, it would fail to compile.
Should I move the commons-lang to windup-utils and depend on that then?

**Comment by jsight** [comment]
It is worse as you are now classloading commons-utils 3 more times than before.

**Comment by OndraZizka** [comment]
That's a fair point, but I thought that's a sacrifice you give when using modules :) So what do you suggest?

**Comment by jsight** [comment]
Previously, I think that graph was exposing commons-lang. Now perhaps windup-utils could do it instead (as you were suggesting)?

**Comment by OndraZizka** [comment]
okok

**Comment by OndraZizka** [comment]
Changed as per comments above, and rebased. -> tests

**Comment by jsight** [comment]
Ok, I will look again soon.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Pull request merged**
