### PR TITLE
WINDUP-4139: upgrade axios

### PR DESCRIPTION
**Pull request by m-brophy**
https://issues.redhat.com/browse/WINDUP-4139

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@carlosthe19916 Can you review this PR please?

**Review by carlosthe19916 — CHANGES_REQUESTED** [review]
When the dependency to be upgraded is a direct dependency (a dependency that appear in the package.json file) then using the `overrides` section is not good.

Please locally remove all your changes and you can do:

```shell
npm ci
npm install axios@1.6.0 --save-exact
```

That should make sure the direct dependency is updated

**Review by carlosthe19916 — APPROVED** [review]
LGTM! Thanks @m-brophy

**Comment by m-brophy** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|releases/6.3.z|[](https://github.com/windup/windup/pull/1732)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
