### PR TITLE
Add furnace-maven-plugin to BOM.

### PR DESCRIPTION
**Pull request by OndraZizka**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/645/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/15/
Test FAILed.

**Comment by jsight** [comment]
Shouldn't this just be in the forge bom?

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/28/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/658/
Test PASSed.

**Comment by lincolnthree** [comment]
Actually yes, it should just be in the Forge BOM. @gastaldi wdyt?

**Comment by gastaldi** [comment]
Is it possible to declare plugin versions in <dependencyManagement> ? I thought they could only be used inside <pluginManagement>.

**Comment by jsight** [comment]
@gastaldi I think you need to escape the &lt; and &gt; tags. :)

**Comment by gastaldi** [comment]
I edited the comment. Thanks @jsight :) In this case, if this works, it should be in the furnace-bom instead.

**Comment by jsight** [comment]
@gastaldi I wondered the same thing. I am not sure that this solution works.

**Comment by gastaldi** [comment]
Just tested, it does not work: 
[WARNING] Some problems were encountered while building the effective model for org.jboss.forge:forge-distribution:pom:2.15.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.jboss.forge.furnace:furnace-maven-plugin is missing. @ org.jboss.forge:forge-distribution:[unknown-version], /usr/local/workspace/forge-core-2.0/dist/pom.xml, line 25, column 18

**Comment by gastaldi** [comment]
I really wish this worked, so we would not need to change the furnace.version in two places as it is now: eg: https://github.com/forge/core/commit/97a9454f47faed1c6423f52defd315ac6d2158f6

**Comment by jsight** [comment]
Ok, thanks @gastaldi. I think this can be closed then.

**Pull request closed without merging**
