### PR TITLE
WINDUP-1015: <description> value taken instead of <name> to create Pr…

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-1015

### CODE REVIEW

**Comment by OndraZizka** [comment]
Great! :)

**Comment by OndraZizka** [comment]
Where was the value being taken from? MANIFEST? In that case, shouldn't we still have a look what's taken from MANIFEST? If it was taking Specification-Title: and that's often a long description, maybe we should use some other value.

**Comment by jsight** [comment]
I don't think that it is obvious that Specification-TItle is any worse or better than Implementation-Title. It seems like Maven builds stuff the description there, but with Maven builds we have the POM to pull from.

With manually put together manifests (or maybe other build systems?), often the implementation-title will be garbage (just a package name or something) when the specification-title is good. Its really just a guess at that point.

**Comment by OndraZizka** [comment]
MANIFEST "spec": https://docs.oracle.com/javase/tutorial/deployment/jar/packageman.html

**Comment by OndraZizka** [comment]
For mavenization, Impl-Title might be better

**Pull request merged**
