### PR TITLE
WINDUP-581 - Maven and License File Classification & Tagging.

### PR DESCRIPTION
**Pull request by bradsdavis**

### CODE REVIEW

**Comment by lincolnthree** [comment]
Awesome! Thanks brad.

**Comment by lincolnthree** [comment]
test this please

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/760/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.jboss.windup:windup-tooling-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/760/org.jboss.windup$windup-tooling-tests/testReport'>org.jboss.windup:windup-tooling-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/760/org.jboss.windup$windup-tooling-tests/testReport/org.jboss.windup.tooling/ExecutionBuilderTest/testExecutionBuilder/'><strong>org.jboss.windup.tooling.ExecutionBuilderTest.testExecutionBuilder</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/129/
Test PASSed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-pr-builder/761/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='org.jboss.windup:windup-tooling-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/761/org.jboss.windup$windup-tooling-tests/testReport'>org.jboss.windup:windup-tooling-tests</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/761/org.jboss.windup$windup-tooling-tests/testReport/org.jboss.windup.tooling/ExecutionBuilderTest/testExecutionBuilder/'><strong>org.jboss.windup.tooling.ExecutionBuilderTest.testExecutionBuilder</strong></a></li></ul><h3><a name='org.jboss.windup.tests:windup-tests' /><a href='http://10.3.8.5/job/windup-pr-builder/761/org.jboss.windup.tests$windup-tests/testReport'>org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>2</span></h3><ul><li><a href='http://10.3.8.5/job/windup-pr-builder/761/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJEEExampleTest/testRunWindupJEEExampleMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureJEEExampleTest.testRunWindupJEEExampleMode</strong></a></li><li><a href='http://10.3.8.5/job/windup-pr-builder/761/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li></ul>
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-core-PR-dependents-check/130/
Test PASSed.

**Pull request merged**
