### PR TITLE
WINDUP-900: The application list should display effort categories

### PR DESCRIPTION
**Pull request by jsight**
https://issues.jboss.org/browse/WINDUP-900

### CODE REVIEW

**Comment by mareknovotny** [comment]
I am little puzzled with the summary numbers for instance in case of jee-example-app-1.0.0.ear report.
It shows 
44 - Trivial incidents
13 - Complex incidents
57 Total Incidents
83 Total Effort Points 

where I wasn't able to find out *44 Trivial incidents* and then the sum of incidents is wrong IMO or not clear to me.

**Comment by mareknovotny** [comment]
ok, after a discussion with @jsight on IRC I got what those numbers are. The content is listed on Migration Issues Report table ;)

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/793/

**Comment by mareknovotny** [comment]
I still don't like the text is in that cell.
what about this rewording and adding a column to split total SP from the severity counts? I tried to mock it on the generated report like this 
screenshot from 2016-02-05 11-36-32
Certainly it needs to be properly aligned too.

**Comment by jsight** [comment]
I think that is a good idea, but "Issues" is going to have to be called "Incidents". I will try this today.

**Comment by mareknovotny** [comment]
true, that will reduce the need to have "Incidents" behind number ;)

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1433/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='windup-pr-builder/org.jboss.windup.tests:windup-tests' /><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1433/org.jboss.windup.tests$windup-tests/testReport'>windup-pr-builder/org.jboss.windup.tests:windup-tests</a>: <span class='status-failure'>3</span></h3><ul><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1433/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureCatchallTest/testRunWindupJsp/'><strong>org.jboss.windup.tests.application.WindupArchitectureCatchallTest.testRunWindupJsp</strong></a></li><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1433/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureJspTest/testRunWindupJsp/'><strong>org.jboss.windup.tests.application.WindupArchitectureJspTest.testRunWindupJsp</strong></a></li><li><a href='http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1433/org.jboss.windup.tests$windup-tests/testReport/org.jboss.windup.tests.application/WindupArchitectureSourceModeTest/testRunWindupSourceMode/'><strong>org.jboss.windup.tests.application.WindupArchitectureSourceModeTest.testRunWindupSourceMode</strong></a></li></ul>

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/811/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1434/

**Comment by mareknovotny** [comment]
it seems ok, even Tobias would like to have all numbers aligned to right (Total SP value is left aligned), but this could be done generally in all reports later. So +1

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1435/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/813/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-pr-builder/1436/

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://wonka.mw.lab.eng.bos.redhat.com/jenkins//job/windup-core-PR-dependents-check/814/

**Pull request merged**
