### PR TITLE
WINDUP-398 + WINDUP-459  IdentifyArchives + SkipArhives

### PR DESCRIPTION
**Pull request by OndraZizka**
WINDUP-459 Rules request: Support ignoring jars by G:A:V and hashes
WINDUP-398 Rules request: Identify archives by their hash

Not finished:
rules-java-archives TODOs:
--------------------------
Resource loading doesnt work in IdentifyArchivesLoadConfigRules
IdentArch -> rename strings and messages to rules-java-archives or such
SkippedArchives is now static class as is the ArchiveGAVIdentifier, that would be nicer if some normal service bean or such
Blend the RuleFilters with existing "Predicates" (BTW I don't like the name predicate while it's just a filter)
Split the test for loading of bundled data and actual identification (ArchiveGAVIdentifier.addMapping("4e031bb61df09069aeb2bffb4019e7a5034a4ee0", "junit:junit:4.11");)

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build triggered.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/435/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Merged build started.

**Comment by windupgithubbot1** [comment]
Merged build finished. Test FAILed.

**Comment by windupgithubbot1** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/436/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/445/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/447/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/448/
Test FAILed.

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://10.3.9.192//job/windup-pr-builder/449/
Test FAILed.

**Comment by lincolnthree** [comment]
Included in #456

**Pull request closed without merging**
