### PR TITLE
org.json:json:20160810

### PR DESCRIPTION
**Pull request by OndraZizka**
Trying if it would work. Currently we are using version 2008-something.
1) The old versions are very buggy
2) Can't serialize proxies
3) The API is supposedly the same.

### CODE REVIEW

**Comment by jsight** [comment]
I didn't think that we used this at all? Does jackson use this somehow?

**Comment by jsight** [comment]
Oh, I see... jackson uses org.json underneath. I wonder why it uses an older version? In any case, I'm not really sure that serializing the proxies is a good idea in general.

**Comment by jsight** [comment]
retest

**Comment by mareknovotny** [comment]
it seems github shows wrongly failure in test while http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-pr-builder/1926/ and http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/1308/ both passed.

**Comment by mareknovotny** [comment]
retest

**Comment by mareknovotny** [comment]
I know it passed both CI jobs before, but just for testing github to show real test status ;)

**Comment by mareknovotny** [comment]
so are we ready to merge this? the last time to object ;)

**Comment by jsight** [comment]
I think this is ok to merge.

**Pull request merged**
